// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "beasts of chaos",
    warscrolls: {
        "Gors" : {
            baseSize: "32mm",
            notes: "",
        },
        "Morghurite Chaos Spawn (Gibbering Congregation)" : {
            baseSize: "Single. Can only be included in a Gavespawn army. These units must be taken as a set referred to as a Gibbering Congregation.",
            notes: "",
        },
        "Although taken as a set, each is a separate unit." : {
            baseSize: "50mm",
            notes: "",
        },
        "Morghurite Chaos Spawn (Gibbering Congregation)" : {
            baseSize: "Battleline",
            notes: "",
        },
        "Morghurite Chaos Spawn (Gibbering Congregation)" : {
            baseSize: "Battleline",
            notes: "",
        },
        "Ungors" : {
            baseSize: "25mm",
            notes: "",
        },
        "Chaos Gargant" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Chimera" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Cygor" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Ghorgon" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Jabberslythe" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Beastlord" : {
            baseSize: "40mm",
            notes: "",
        },
        "Beasts of Chaos Tzaangor Shaman" : {
            baseSize: "40mm",
            notes: "",
        },
        "Doombull" : {
            baseSize: "50mm",
            notes: "",
        },
        "Dragon Ogor Shaggoth" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Grashrak Fellhoof" : {
            baseSize: "32mm",
            notes: "",
        },
        "Grashrak’s Despoilers" : {
            baseSize: "32mm [1], 25mm [4]",
            notes: "",
        },
        "Great Bray-Shaman" : {
            baseSize: "32mm",
            notes: "",
        },
        "Beasts of Chaos Chaos Spawn" : {
            baseSize: "50mm",
            notes: "",
        },
        "Beasts of Chaos Slaangor Fiendbloods" : {
            baseSize: "40mm",
            notes: "",
        },
        "Beasts of Chaos Tzaangor Enlightened" : {
            baseSize: "40mm",
            notes: "",
        },
        "Beasts of Chaos Tzaangor Enlightened on Discs of Tzeentch" : {
            baseSize: "40mm",
            notes: "",
        },
        "Beasts of Chaos Tzaangor Skyfires" : {
            baseSize: "40mm",
            notes: "",
        },
        "Beasts of Chaos Tzaangors" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bestigors" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bullgors" : {
            baseSize: "50mm",
            notes: "",
        },
        "Centigors" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Chaos Warhounds" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Cockatrice" : {
            baseSize: "60mm",
            notes: "",
        },
        "Dragon Ogors" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Razorgors" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Tuskgor Chariots" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Ungor Raiders" : {
            baseSize: "25mm",
            notes: "",
        },
        "Doomblast Dirgehorn" : {
            baseSize: "40mm",
            notes: "",
        },
        "Ravening Direflock" : {
            baseSize: "40mm",
            notes: "",
        },
        "Wildfire Taurus" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Herdstone" : {
            baseSize: "Use model",
            notes: "",
        },
    }
}
export default Warscrolls