// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "blades of khorne",
    warscrolls: {
        "Aspiring Deathbringer" : {
            baseSize: "32mm",
            notes: "",
        },
        "Aspiring Deathbringer with Goreaxe and Skullhammer" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bleeding Icon" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Blood Throne" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Blood Warriors" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bloodcrushers" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Bloodletters" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bloodmaster, Herald of Khorne" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bloodreavers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bloodsecrator" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bloodstoker" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bloodthirster of Insensate Rage" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Bloodthirster of Unfettered Fury" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Exalted Deathbringer with Bloodbite Axe" : {
            baseSize: "40mm",
            notes: "",
        },
        "Exalted Deathbringer with Impaling Spear" : {
            baseSize: "40mm",
            notes: "",
        },
        "Exalted Deathbringer with Ruinous Axe" : {
            baseSize: "40mm",
            notes: "",
        },
        "Exalted Greater Daemon of Khorne" : {
            baseSize: "160mm",
            notes: "",
        },
        "Flesh Hounds" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Garrek’s Reavers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Hexgorger Skulls" : {
            baseSize: "60mm",
            notes: "",
        },
        "Karanak" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Khorgoraths" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Korghos Khul" : {
            baseSize: "60mm",
            notes: "",
        },
        "Lord of Khorne on Juggernaut" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Magore’s Fiends" : {
            baseSize: "32mm",
            notes: "",
        },
        "Mazarall the Butcher" : {
            baseSize: "100mm",
            notes: "",
        },
        "Mighty Lord of Khorne" : {
            baseSize: "60mm",
            notes: "",
        },
        "Mighty Skullcrushers" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Riptooth" : {
            baseSize: "50mm",
            notes: "",
        },
        "Scyla Anfingrimm" : {
            baseSize: "60mm",
            notes: "",
        },
        "Skaarac the Bloodborn" : {
            baseSize: "160mm",
            notes: "",
        },
        "Skarbrand" : {
            baseSize: "100mm",
            notes: "",
        },
        "Skarr Bloodwrath" : {
            baseSize: "40mm",
            notes: "",
        },
        "Skull Cannons" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Skullgrinder" : {
            baseSize: "40mm",
            notes: "",
        },
        "Skullmaster, Herald of Khorne" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Skullreapers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Skulltaker" : {
            baseSize: "40mm",
            notes: "",
        },
        "Slaughterbrute of Khorne" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Slaughterpriest" : {
            baseSize: "40mm",
            notes: "",
        },
        "Slaughterpriest with Hackblade and Wrath-hammer" : {
            baseSize: "40mm",
            notes: "",
        },
        "Valkia the Bloody" : {
            baseSize: "32mm",
            notes: "",
        },
        "Wrath of Khorne Bloodthirster" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Wrath-axe" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Wrathmongers" : {
            baseSize: "40mm",
            notes: "",
        },
    }
}
export default Warscrolls