// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "blades of khorne",
    warscrolls: {
        "Skull Cannon" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Bloodletters" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bloodreavers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Blood Warriors" : {
            baseSize: "32mm",
            notes: "",
        },
        "Claws of Karanak" : {
            baseSize: "40mm [1], 60 x 35mm [1], 32mm [2], 28mm [4]",
            notes: "",
        },
        "Flesh Hounds" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Aspiring Deathbringer" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bloodmaster, Herald of Khorne" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bloodsecrator" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bloodstoker" : {
            baseSize: "40mm",
            notes: "",
        },
        "Dromm, Wounder of Worlds" : {
            baseSize: "40mm",
            notes: "",
        },
        "Gorechosen of Dromm" : {
            baseSize: "40mm [1], 32mm [1]",
            notes: "",
        },
        "Exalted Deathbringer" : {
            baseSize: "40mm",
            notes: "",
        },
        "Herald of Khorne on Blood Throne" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Korghos Khul" : {
            baseSize: "60mm",
            notes: "",
        },
        "Lord of Khorne on Juggernaut" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Mighty Lord of Khorne" : {
            baseSize: "60mm",
            notes: "",
        },
        "Realmgore Ritualist" : {
            baseSize: "32mm",
            notes: "",
        },
        "Scyla Anfingrimm" : {
            baseSize: "60mm",
            notes: "",
        },
        "Skarr Bloodwrath" : {
            baseSize: "40mm",
            notes: "",
        },
        "Skullgrinder" : {
            baseSize: "40mm",
            notes: "",
        },
        "Skullmaster, Herald of Khorne" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Skulltaker" : {
            baseSize: "40mm",
            notes: "",
        },
        "Slaughterpriest" : {
            baseSize: "40mm",
            notes: "",
        },
        "Valkia the Bloody" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bloodthirster of Insensate Rage" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Bloodthirster of Unfettered Fury" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Skarbrand" : {
            baseSize: "100mm",
            notes: "",
        },
        "Wrath of Khorne Bloodthirster" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Bloodcrushers" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Garrek's Reavers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Karanak" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Khorgorath" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Magore's Fiends" : {
            baseSize: "32mm",
            notes: "",
        },
        "Mighty Skullcrushers" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Skullreapers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Wrathmongers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bleeding Icon" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Hexgorger Skulls" : {
            baseSize: "60mm",
            notes: "",
        },
        "Wrath-axe" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Skull Altar" : {
            baseSize: "Use model",
            notes: "",
        },
    }
}
export default Warscrolls