// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "cities of sigmar",
    warscrolls: {
        "Helblaster Volley Gun" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Helstorm Rocket Battery" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Bleakswords" : {
            baseSize: "25mm",
            notes: "",
        },
        "Darkshards" : {
            baseSize: "25mm",
            notes: "",
        },
        "Dreadspears" : {
            baseSize: "25mm",
            notes: "",
        },
        "Eternal Guard" : {
            baseSize: "25mm",
            notes: "",
        },
        "Freeguild Crossbowmen" : {
            baseSize: "25mm",
            notes: "",
        },
        "Freeguild Guard" : {
            baseSize: "25mm",
            notes: "",
        },
        "Freeguild Handgunners" : {
            baseSize: "25mm",
            notes: "",
        },
        "Ironbreakers" : {
            baseSize: "25mm",
            notes: "",
        },
        "Longbeards" : {
            baseSize: "25mm",
            notes: "",
        },
        "Celestial Hurricanum" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Flamespyre Phoenix" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Frostheart Phoenix" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Kharibdyss" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Luminark of Hysh" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Steam Tank" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "War Hydra" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Anointed" : {
            baseSize: "25mm",
            notes: "",
        },
        "Assassin" : {
            baseSize: "25mm",
            notes: "",
        },
        "Battlemage" : {
            baseSize: "25mm",
            notes: "",
        },
        "Black Ark Fleetmaster" : {
            baseSize: "25mm",
            notes: "",
        },
        "Cogsmith" : {
            baseSize: "25mm",
            notes: "",
        },
        "Doralia ven Denst" : {
            baseSize: "28.5mm",
            notes: "",
        },
        "Freeguild General" : {
            baseSize: "25mm",
            notes: "",
        },
        "Galen ven Denst" : {
            baseSize: "28.5mm",
            notes: "",
        },
        "Haskel Hexbane" : {
            baseSize: "28.5mm",
            notes: "",
        },
        "Hexbane’s Hunters" : {
            baseSize: "25mm [2], 28.5mm [2], 32mm [1]",
            notes: "",
        },
        "Nomad Prince" : {
            baseSize: "32mm",
            notes: "",
        },
        "Runelord" : {
            baseSize: "25mm",
            notes: "",
        },
        "Sorceress" : {
            baseSize: "25mm",
            notes: "",
        },
        "Warden King" : {
            baseSize: "25mm",
            notes: "",
        },
        "Anointed on Flamespyre Phoenix" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Anointed on Frostheart Phoenix" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Battlemage on Griffon" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Celestial Hurricanum with Celestial Battlemage" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Dreadlord on Black Dragon" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Freeguild General on Griffon" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Luminark of Hysh with White Battlemage" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Sorceress on Black Dragon" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Steam Tank with Commander" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Black Ark Corsairs" : {
            baseSize: "25mm",
            notes: "",
        },
        "Black Guard" : {
            baseSize: "25mm",
            notes: "",
        },
        "Dark Riders" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Demigryph Knights" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Drakespawn Chariots" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Drakespawn Knights" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Executioners" : {
            baseSize: "25mm",
            notes: "",
        },
        "Flagellants" : {
            baseSize: "25mm",
            notes: "",
        },
        "Freeguild Greatswords" : {
            baseSize: "25mm",
            notes: "",
        },
        "Freeguild Outriders" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Freeguild Pistoliers" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Gyrobombers" : {
            baseSize: "50mm",
            notes: "",
        },
        "Gyrocopters" : {
            baseSize: "50mm",
            notes: "",
        },
        "Hammerers" : {
            baseSize: "25mm",
            notes: "",
        },
        "Irondrakes" : {
            baseSize: "25mm",
            notes: "",
        },
        "Phoenix Guard" : {
            baseSize: "25mm",
            notes: "",
        },
        "Scourgerunner Chariots" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Shadow Warriors" : {
            baseSize: "25mm",
            notes: "",
        },
        "Sisters of the Thorn" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Sisters of the Watch" : {
            baseSize: "25mm",
            notes: "",
        },
        "Wild Riders" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Wildwood Rangers" : {
            baseSize: "25mm",
            notes: "",
        },
    }
}
export default Warscrolls