// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "cursed city",
    warscrolls: {
        "Jelsen Darrock" : {
            baseSize: "32mm",
            notes: "",
        },
        "Captain Emelda Braskow" : {
            baseSize: "32mm",
            notes: "",
        },
        "Qulathis the Exile" : {
            baseSize: "32mm",
            notes: "",
        },
        "Dagnai Holdenstock" : {
            baseSize: "32mm",
            notes: "",
        },
        "Brutogg Corpse-Eater" : {
            baseSize: "40mm",
            notes: "",
        },
        "Cleona Zeitengale" : {
            baseSize: "32mm",
            notes: "",
        },
        "Glaurio Ven Alten III" : {
            baseSize: "32mm",
            notes: "",
        },
        "Octren Glimscry" : {
            baseSize: "32mm",
            notes: "",
        },
        "Radukar the Wolf" : {
            baseSize: "40mm",
            notes: "",
        },
        "Torgillius the Chamberlain" : {
            baseSize: "40mm",
            notes: "",
        },
        "Watch Captain Halgrim" : {
            baseSize: "32mm",
            notes: "",
        },
        "Korsargi Nightguard" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vyrkos Blood-Born" : {
            baseSize: "32mm",
            notes: "",
        },
        "Gorslav the Gravekeeper" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vargskyr" : {
            baseSize: "50mm",
            notes: "",
        },
    }
}
export default Warscrolls