// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "daughters of khaine",
    warscrolls: {
        "Sisters of Slaughter" : {
            baseSize: "25mm",
            notes: "",
        },
        "Witch Aelves" : {
            baseSize: "25mm",
            notes: "",
        },
        "Avatar of Khaine" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bloodwrack Medusa" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bloodwrack Shrine" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Hag Queen" : {
            baseSize: "25mm",
            notes: "",
        },
        "High Gladiatrix" : {
            baseSize: "32mm",
            notes: "",
        },
        "Melusai Ironscale" : {
            baseSize: "40mm",
            notes: "",
        },
        "Morathi-Khaine" : {
            baseSize: "40mm",
            notes: "",
        },
        "The Shadow Queen" : {
            baseSize: "100mm",
            notes: "",
        },
        "Morgwaeth the Bloodied" : {
            baseSize: "32mm",
            notes: "",
        },
        "The Blade-coven" : {
            baseSize: "32mm [3], 40mm [1]",
            notes: "",
        },
        "Slythael Shadestalker" : {
            baseSize: "40mm",
            notes: "",
        },
        "The Shadeborn" : {
            baseSize: "28.5mm",
            notes: "",
        },
        "Slaughter Queen" : {
            baseSize: "25mm",
            notes: "",
        },
        "Hag Queen on Cauldron of Blood" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Slaughter Queen on Cauldron of Blood" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Blood Sisters" : {
            baseSize: "40mm",
            notes: "",
        },
        "Blood Stalkers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Doomfire Warlocks" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Gryselle's Arenai" : {
            baseSize: "32mm [1], 28.5mm [4]",
            notes: "",
        },
        "Khainite Shadowstalkers" : {
            baseSize: "28.5mm",
            notes: "",
        },
        "Khinerai Heartrenders" : {
            baseSize: "40mm",
            notes: "",
        },
        "Khinerai Lifetakers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bladewind" : {
            baseSize: "50mm",
            notes: "",
        },
        "Bloodwrack Viper" : {
            baseSize: "100mm",
            notes: "",
        },
        "Heart of Fury" : {
            baseSize: "50mm",
            notes: "",
        },
    }
}
export default Warscrolls