// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "disciples of tzeentch",
    warscrolls: {
        "Jade Obelisk" : {
            baseSize: "32mm [5], 28.5mm [5]",
            notes: "",
        },
        "Kairic Acolytes" : {
            baseSize: "32mm",
            notes: "",
        },
        "Tzaa ngors" : {
            baseSize: "32mm",
            notes: "",
        },
        "The Blue Scribes" : {
            baseSize: "60mm",
            notes: "",
        },
        "Changecaster, Herald of Tzeentch" : {
            baseSize: "32mm",
            notes: "",
        },
        "The Changeling" : {
            baseSize: "40mm",
            notes: "",
        },
        "Curseling, Eye of Tzeentch" : {
            baseSize: "32mm",
            notes: "",
        },
        "Ephilim the Unknowable" : {
            baseSize: "32mm",
            notes: "",
        },
        "Ephilim’s Pandaemonium" : {
            baseSize: "32mm [2], 25mm [2]",
            notes: "",
        },
        "Fatemaster" : {
            baseSize: "60mm",
            notes: "",
        },
        "Fateskimmer, Herald of Tzeentch on Burning Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Fluxmaster, Herald of Tzeentch on Disc" : {
            baseSize: "60mm",
            notes: "",
        },
        "Gaunt Summoner" : {
            baseSize: "40mm",
            notes: "",
        },
        "Gaunt Summoner on Disc of Tzeentch" : {
            baseSize: "40mm",
            notes: "",
        },
        "Magister" : {
            baseSize: "32mm",
            notes: "",
        },
        "Magister on Disc of Tzeentch" : {
            baseSize: "50mm",
            notes: "",
        },
        "Ogroid Thaumaturge" : {
            baseSize: "50mm",
            notes: "",
        },
        "Tzaangor Shaman" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vortemis the All-seeing" : {
            baseSize: "32mm",
            notes: "",
        },
        "The Eyes of the Nine" : {
            baseSize: "32mm [3], 25mm [2]",
            notes: "",
        },
        "Kairos Fateweaver" : {
            baseSize: "100mm",
            notes: "",
        },
        "Lord of Change" : {
            baseSize: "100mm",
            notes: "",
        },
        "Burning Chariots of Tzeentch" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Disciples of Tzeentch Chaos Spawn" : {
            baseSize: "50mm",
            notes: "",
        },
        "Exalted Flamers of Tzeentch" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Flamers of Tzeentch" : {
            baseSize: "32mm",
            notes: "",
        },
        "Horrors of Tzeentch" : {
            baseSize: "32mm ",
            notes: "(Pink), 25mm (Blue/Bri mstone)",
        },
        "Screamers of Tzeentch" : {
            baseSize: "32mm",
            notes: "",
        },
        "Tzaangor Enlightened" : {
            baseSize: "40mm",
            notes: "",
        },
        "Tzaangor Enlightened on Discs of Tzeentch" : {
            baseSize: "40mm",
            notes: "",
        },
        "Tzaangor Skyfires" : {
            baseSize: "40mm",
            notes: "",
        },
        "Burning Sigil of Tzeentch" : {
            baseSize: "50mm",
            notes: "",
        },
        "Daemonic Simulacrum" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Tome of Eyes" : {
            baseSize: "50mm",
            notes: "",
        },
    }
}
export default Warscrolls