// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "endless spells",
    warscrolls: {
        "Aethervoid Pendulum" : {
            baseSize: "Custom 64 x 42mm ",
            notes: "(Official document says 'Use Model')",
        },
        "The Burning Head" : {
            baseSize: "50mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Chronomantic Cogs" : {
            baseSize: "40mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Emerald Lifeswarm" : {
            baseSize: "Custom 64 x 42mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Geminids of Uhl-Gysh" : {
            baseSize: "40mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Horrorghast" : {
            baseSize: "50mm",
            notes: "",
        },
        "Lauchon the Soulseeker" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Malevolent Maelstrom" : {
            baseSize: "50mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Prismatic Palisade" : {
            baseSize: "Irregular 177 x 32mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Purple Sun of Shyish" : {
            baseSize: "100 x 70mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Quicksilver Swords" : {
            baseSize: "40mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Ravenak's Gnashing Jaws" : {
            baseSize: "100 x 70mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Shards of Valagharr" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Soulscream Bridge" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Soulsnare Shackles" : {
            baseSize: "40mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Suffocating Gravetide" : {
            baseSize: "Irregular 170 x 85mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Umbral Spellportal" : {
            baseSize: "40mm ",
            notes: "(Official document says 'Use Model')",
        },
    }
}
export default Warscrolls