// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "endless spells",
    warscrolls: {
        "Aethervoid Pendulum" : {
            baseSize: "Use model",
            notes: "",
        },
        "The Burning Head" : {
            baseSize: "Use model",
            notes: "",
        },
        "Chronomantic Cogs" : {
            baseSize: "Use model",
            notes: "",
        },
        "Emerald Lifeswarm" : {
            baseSize: "Use model",
            notes: "",
        },
        "Geminids of Uhl-Gysh" : {
            baseSize: "Use model",
            notes: "",
        },
        "Horrorghast" : {
            baseSize: "50mm",
            notes: "",
        },
        "Lauchon the Soulseeker" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Malevolent Maelstrom" : {
            baseSize: "Use model",
            notes: "",
        },
        "Prismatic Palisade" : {
            baseSize: "Use model",
            notes: "",
        },
        "Purple Sun of Shyish" : {
            baseSize: "Use model",
            notes: "",
        },
        "Quicksilver Swords" : {
            baseSize: "Use model",
            notes: "",
        },
        "Ravenak's Gnashing Jaws" : {
            baseSize: "Use model",
            notes: "",
        },
        "Shards of Valagharr" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Soulscream Bridge" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Soulsnare Shackles" : {
            baseSize: "Use model",
            notes: "",
        },
        "Suffocating Gravetide" : {
            baseSize: "Use model",
            notes: "",
        },
        "Umbral Spellportal" : {
            baseSize: "Use model",
            notes: "",
        },
    }
}
export default Warscrolls