// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "fimir",
    warscrolls: {
        "Fimirach Noble" : {
            baseSize: "50mm",
            notes: "(No longer in pdf)",
        },
        "Fimir Warriors" : {
            baseSize: "50mm",
            notes: "(No longer in pdf)",
        },
    }
}
export default Warscrolls