// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "flesheater courts",
    warscrolls: {
        "Crypt Ghouls" : {
            baseSize: "25mm",
            notes: "",
        },
        "Royal Terrorgheist" : {
            baseSize: "130mm",
            notes: "",
        },
        "Royal Zombie Dragon" : {
            baseSize: "130mm",
            notes: "",
        },
        "Abhorrant Archregent" : {
            baseSize: "40mm",
            notes: "",
        },
        "Abhorrant Ghoul King" : {
            baseSize: "32mm",
            notes: "",
        },
        "Crypt Ghast Courtier" : {
            baseSize: "32mm",
            notes: "",
        },
        "Crypt Haunter Courtier" : {
            baseSize: "50mm",
            notes: "",
        },
        "Crypt Infernal Courtier" : {
            baseSize: "50mm",
            notes: "",
        },
        "Duke Crakmarrow" : {
            baseSize: "32mm",
            notes: "",
        },
        "The Grymwatch" : {
            baseSize: "32mm [1], 25mm [5]",
            notes: "",
        },
        "Marrowscroll Herald" : {
            baseSize: "32 mm",
            notes: "",
        },
        "Varghulf Courtier" : {
            baseSize: "60mm",
            notes: "",
        },
        "Abhorrant Ghoul King on Royal Terrorgheist" : {
            baseSize: "130mm",
            notes: "",
        },
        "Abhorrant Ghoul King on Royal Zombie Dragon" : {
            baseSize: "130mm",
            notes: "",
        },
        "Nagash, Supreme Lord of the Undead" : {
            baseSize: "130mm",
            notes: "",
        },
        "Crypt Flayers" : {
            baseSize: "50mm",
            notes: "",
        },
        "Crypt Horrors" : {
            baseSize: "50mm",
            notes: "",
        },
        "Royal Beastflayers" : {
            baseSize: "32mm [2], 40mm [2], 28mm [3], 25m m [3]",
            notes: "",
        },
        "Cadaverous Barricade" : {
            baseSize: "Use model",
            notes: "",
        },
        "Chalice of Ushoran" : {
            baseSize: "50mm",
            notes: "",
        },
        "Corpsemare Stampede" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Charnel Throne" : {
            baseSize: "Use model",
            notes: "",
        },
    }
}
export default Warscrolls