// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "forbidden power",
    warscrolls: {
        "Horrorghast" : {
            baseSize: "50mm",
            notes: "",
        },
        "Lauchon the Soulseeker" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Shards of Valagharr" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Soulscream Bridge" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
    }
}
export default Warscrolls