// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "fyreslayers",
    warscrolls: {
        "Vulkite Berzerkers with Bladed Slingshields" : {
            baseSize: "32mm",
            notes: "",
        },
        "Vulkite Berzerkers with Fyresteel Handaxes" : {
            baseSize: "32mm",
            notes: "",
        },
        "Auric Flamekeeper" : {
            baseSize: "32mm",
            notes: "",
        },
        "Auric Runefather" : {
            baseSize: "32mm",
            notes: "",
        },
        "Auric Runemaster" : {
            baseSize: "32mm",
            notes: "",
        },
        "Auric Runesmiter" : {
            baseSize: "32mm",
            notes: "",
        },
        "Auric Runeson" : {
            baseSize: "32mm",
            notes: "",
        },
        "Battlesmith" : {
            baseSize: "32mm",
            notes: "",
        },
        "Fjul-Grimnir" : {
            baseSize: "32mm",
            notes: "",
        },
        "The Chosen Axes" : {
            baseSize: "3",
            notes: "",
        },
        "Auric Runefather on Magmadroth" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Grimhold Exile" : {
            baseSize: "32mm",
            notes: "",
        },
        "Auric Runesmiter on Magmadroth" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Auric Runeson on Magmadroth" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Auric Hearthguard" : {
            baseSize: "32mm",
            notes: "",
        },
        "Doomseeker" : {
            baseSize: "32mm",
            notes: "",
        },
        "Grimwrath Berzerker" : {
            baseSize: "32mm",
            notes: "",
        },
        "Hearthguard Berzerkers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Molten Infernoth" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Runic Fyrewall" : {
            baseSize: "Use model",
            notes: "",
        },
        "Zharrgron Flame-spitter" : {
            baseSize: "Use model",
            notes: "",
        },
        "Magmic Battleforge" : {
            baseSize: "Use model",
            notes: "",
        },
    }
}
export default Warscrolls