// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "gitmob grots",
    warscrolls: {
        "Doom Diver Catapult" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Doom Diver Catapult Crew with Rope" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Doom Diver Catapult Crew with Hammer" : {
            baseSize: "25mm",
            notes: "",
        },
        "Doom Diver" : {
            baseSize: "32mm",
            notes: "",
        },
        "Grot Rock Lobber" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Grot Rock Lobber Crew" : {
            baseSize: "25mm",
            notes: "",
        },
        "Grot Rock Lobber Orruk Bully" : {
            baseSize: "32mm",
            notes: "",
        },
        "Grot Shaman" : {
            baseSize: "25mm",
            notes: "",
        },
        "Grot Shaman on Wolf" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Grot Spear Chukka" : {
            baseSize: "50mm",
            notes: "",
        },
        "Grot Spear Chukka Crew" : {
            baseSize: "25mm",
            notes: "",
        },
        "Grot Wolf Chariots" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Grot Wolf Riders" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Grots" : {
            baseSize: "25mm",
            notes: "",
        },
        "Nasty Skulkers" : {
            baseSize: "25mm",
            notes: "",
        },
        "Snotling Pump Wagons" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Snotlings" : {
            baseSize: "50mm",
            notes: "",
        },
    }
}
export default Warscrolls