// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "gloomspite gitz",
    warscrolls: {
        "Moonclan Shootas" : {
            baseSize: "25mm",
            notes: "",
        },
        "Moonclan Stabbas" : {
            baseSize: "25mm",
            notes: "",
        },
        "Squig Hoppers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Aleguzzler Gargant" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Arachnarok Spider with Flinger" : {
            baseSize: "160mm",
            notes: "",
        },
        "Arachnarok Spider with Spiderfang Warparty" : {
            baseSize: "160mm",
            notes: "",
        },
        "Mangler Squigs" : {
            baseSize: "80mm",
            notes: "",
        },
        "Skitterstrand Arachnarok" : {
            baseSize: "160mm",
            notes: "",
        },
        "Dankhold Troggboss" : {
            baseSize: "60mm",
            notes: "",
        },
        "Fungoid Cave-Shaman" : {
            baseSize: "32mm",
            notes: "",
        },
        "Grinkrak the Great" : {
            baseSize: "32mm",
            notes: "",
        },
        "Grinkrak's Looncourt" : {
            baseSize: "32mm [2], 25mm [4]",
            notes: "",
        },
        "Loonboss" : {
            baseSize: "32mm",
            notes: "",
        },
        "Loonboss on Giant Cave Squig" : {
            baseSize: "40mm",
            notes: "",
        },
        "Loonboss with Giant Cave Squig" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Madcap Shaman" : {
            baseSize: "25mm",
            notes: "",
        },
        "Mollog" : {
            baseSize: "50mm [1], 25mm [3]",
            notes: "",
        },
        "Rabble-Rowza" : {
            baseSize: "32mm",
            notes: "",
        },
        "Scuttleboss on Gigantic Spider" : {
            baseSize: "60mm",
            notes: "",
        },
        "Skragrott, the Loonking" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Squigboss with Gnasha-squig" : {
            baseSize: "32mm",
            notes: "",
        },
        "Webspinner Shaman" : {
            baseSize: "25mm",
            notes: "",
        },
        "Zarbag" : {
            baseSize: "25mm",
            notes: "",
        },
        "Zarbag's Gitz" : {
            baseSize: "8",
            notes: "",
        },
        "Kragnos, the End of Empires" : {
            baseSize: "130mm",
            notes: "",
        },
        "Loonboss on Mangler Squigs" : {
            baseSize: "80mm",
            notes: "",
        },
        "Webspinner Shaman on Arachnarok Spider" : {
            baseSize: "160mm",
            notes: "",
        },
        "Boingrot Bounderz" : {
            baseSize: "32mm",
            notes: "",
        },
        "Dankhold Troggoths" : {
            baseSize: "60mm",
            notes: "",
        },
        "Fellwater Troggoths" : {
            baseSize: "50mm",
            notes: "",
        },
        "Gobbapalooza" : {
            baseSize: "32mm",
            notes: "",
        },
        "Loonsmasha Fanatics" : {
            baseSize: "32mm",
            notes: "",
        },
        "Rippa's Snarlfangs" : {
            baseSize: "50 x 25mm",
            notes: "",
        },
        "Rockgut Troggoths" : {
            baseSize: "50mm",
            notes: "",
        },
        "Snarlfang Riders" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Sneaky Snufflers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Spider Riders" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Sporesplatta Fanatics" : {
            baseSize: "32mm",
            notes: "",
        },
        "Squig Herd" : {
            baseSize: "25mm",
            notes: "",
        },
        "Malevolent Moon" : {
            baseSize: "50mm",
            notes: "",
        },
        "Mork's Mighty Mushroom" : {
            baseSize: "60mm",
            notes: "",
        },
        "Scrapskuttle's Arachnacauldron" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Scuttletide" : {
            baseSize: "Use model",
            notes: "",
        },
        "Bad Moon Loonshrine" : {
            baseSize: "Use model",
            notes: "",
        },
    }
}
export default Warscrolls