// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "gloomspite gitz",
    warscrolls: {
        "Aleguzzler Gargant" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Arachnarok Spider with Flinger" : {
            baseSize: "160mm",
            notes: "",
        },
        "Arachnarok Spider with Spiderfang Warparty" : {
            baseSize: "160mm",
            notes: "",
        },
        "Boggleye" : {
            baseSize: "32mm",
            notes: "",
        },
        "Boingrot Bounderz" : {
            baseSize: "32mm",
            notes: "",
        },
        "Brewgit" : {
            baseSize: "32mm",
            notes: "",
        },
        "Colossal Squig" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Dankhold Troggboss" : {
            baseSize: "60mm",
            notes: "",
        },
        "Dankhold Troggoths" : {
            baseSize: "60mm",
            notes: "",
        },
        "Fellwater Troggoths" : {
            baseSize: "50mm",
            notes: "",
        },
        "Fungoid Cave-Shaman" : {
            baseSize: "32mm",
            notes: "",
        },
        "Loonboss" : {
            baseSize: "32mm",
            notes: "",
        },
        "Loonboss on Giant Cave Squig" : {
            baseSize: "40mm",
            notes: "",
        },
        "Loonboss on Mangler Squigs" : {
            baseSize: "80mm",
            notes: "",
        },
        "Loonboss with Giant Cave Squig" : {
            baseSize: "60mm",
            notes: "",
        },
        "Loonsmasha Fanatics" : {
            baseSize: "32mm",
            notes: "",
        },
        "Madcap Shaman" : {
            baseSize: "25mm",
            notes: "",
        },
        "Malevolent Moon" : {
            baseSize: "50mm",
            notes: "",
        },
        "Mangler Squigs" : {
            baseSize: "80mm",
            notes: "",
        },
        "Mollog" : {
            baseSize: "50mm",
            notes: "(Minions are 25mm)",
        },
        "Mork’s Mighty Mushroom" : {
            baseSize: "50mm",
            notes: "",
        },
        "Rockgut Troggoths" : {
            baseSize: "50mm",
            notes: "",
        },
        "Scaremonger" : {
            baseSize: "32mm",
            notes: "",
        },
        "Scrapskuttle’s Arachnacauldron" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Scuttleboss on Gigantic Spider" : {
            baseSize: "60mm",
            notes: "",
        },
        "Scuttletide" : {
            baseSize: "Custom base",
            notes: "",
        },
        "Shootas" : {
            baseSize: "25mm",
            notes: "",
        },
        "Shroomancer" : {
            baseSize: "32mm",
            notes: "",
        },
        "Skitterstrand Arachnarok" : {
            baseSize: "160mm",
            notes: "",
        },
        "Skragrott, the Loonking" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Sneaky Snufflers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Spider Riders" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Spiker" : {
            baseSize: "32mm",
            notes: "",
        },
        "Sporesplatta Fanatics" : {
            baseSize: "32mm",
            notes: "",
        },
        "Squig Gobba" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Squig Herd" : {
            baseSize: "25mm",
            notes: "",
        },
        "Squig Hoppers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Stabbas" : {
            baseSize: "25mm",
            notes: "",
        },
        "Troggoth Hag" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Webspinner Shaman" : {
            baseSize: "25mm",
            notes: "",
        },
        "Webspinner Shaman on Arachnarok Spider" : {
            baseSize: "160mm",
            notes: "",
        },
        "Zarbag" : {
            baseSize: "25mm",
            notes: "",
        },
        "Zarbag’s Gitz" : {
            baseSize: "25mm",
            notes: "",
        },
    }
}
export default Warscrolls