// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "gnomad feastmasters",
    warscrolls: {
        "Trailmaster on War-Cockerel" : {
            baseSize: "105 x 70mm",
            notes: "(Fan-made faction)",
        },
        "Hedge Hermit" : {
            baseSize: "25mm",
            notes: "(Fan-made faction)",
        },
        "Mephistio Hartstock" : {
            baseSize: "25mm",
            notes: "(Fan-made faction)",
        },
        "Head Chef" : {
            baseSize: "25mm",
            notes: "(Fan-made faction)",
        },
        "Trail Thief" : {
            baseSize: "25mm",
            notes: "(Fan-made faction)",
        },
        "Yonella Lightfoot" : {
            baseSize: "120 x 92mm",
            notes: "(Fan-made faction)",
        },
        "Arwen ‘Jax Son of the Jade Forest" : {
            baseSize: "105 x 70mm",
            notes: "(Fan-made faction)",
        },
        "Gnomad Drovers" : {
            baseSize: "25mm",
            notes: "(Fan-made faction)",
        },
        "Gastrognome Guard" : {
            baseSize: "60 x 35mm",
            notes: "(Fan-made faction)",
        },
        "Gnomad Scouts" : {
            baseSize: "25mm",
            notes: "(Fan-made faction)",
        },
        "Gryph-Hound Hobelars" : {
            baseSize: "50mm",
            notes: "(Fan-made faction)",
        },
        "Gnomad Scouts riding Jade Eagles" : {
            baseSize: "50mm",
            notes: "(Fan-made faction)",
        },
        "Gastrognome War-Caravan" : {
            baseSize: "120 x 92mm",
            notes: "(Fan-made faction)",
        },
        "Gnomad Hotpot" : {
            baseSize: "50 x 25mm",
            notes: "(Fan-made faction)",
        },
        "Spectral Briar Hedge" : {
            baseSize: "177 x 32mm",
            notes: "(Fan-made faction. See Prismatic Palisade)",
        },
        "Habbinkerr Sentry" : {
            baseSize: "50mm",
            notes: "(Fan-made faction)",
        },
        "Detritus Denizen Swarm" : {
            baseSize: "177 x 32mm",
            notes: "(Fan-made faction. See Prismatic Palisade)",
        },
    }
}
export default Warscrolls