// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "greenskinz",
    warscrolls: {
        "Orruk Boar Chariots" : {
            baseSize: "120 x 92mm",
            notes: "(No longer in pdf)",
        },
        "Orruk Boarboys" : {
            baseSize: "60 x 35mm",
            notes: "(No longer in pdf)",
        },
        "Orruk Great Shaman" : {
            baseSize: "32mm",
            notes: "(No longer in pdf)",
        },
        "Orruk Warboss" : {
            baseSize: "32mm",
            notes: "(No longer in pdf)",
        },
        "Orruk Warboss on War Boar" : {
            baseSize: "60 x 35mm",
            notes: "(No longer in pdf)",
        },
        "Orruk Warboss on Wyvern" : {
            baseSize: "100mm",
            notes: "(No longer in pdf)",
        },
        "Rogue Idol" : {
            baseSize: "170 x 105mm",
            notes: "(No longer in pdf)",
        },
    }
}
export default Warscrolls