// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "hedonites of slaanesh",
    warscrolls: {
        "Bladebringer, Herald on Exalted Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Bladebringer, Herald on Hellflayer" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Bladebringer, Herald on Seeker Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Blissbarb Archers" : {
            baseSize: "28mm",
            notes: "",
        },
        "Blissbarb Seekers" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Blissbrew Homonculus" : {
            baseSize: "25mm",
            notes: "(little friend of Blissbarb Archers)",
        },
        "Daemonettes" : {
            baseSize: "25mm",
            notes: "",
        },
        "Dexcessa, the Talon of Slaanesh" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Dreadful Visage" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Exalted Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Fiends" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Glutos Orscollion, Lord of Gluttony" : {
            baseSize: "170 x 105mm",
            notes: "",
        },
        "Hellflayer" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Hellstriders with Claw-spears" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Hellstriders with Hellscourges" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Infernal Enrapturess, Herald of Slaanesh" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Keeper of Secrets" : {
            baseSize: "100mm",
            notes: "",
        },
        "Lord of Pain" : {
            baseSize: "40mm",
            notes: "",
        },
        "Mesmerising Mirror" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Myrmidesh Painbringers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Seeker Chariots" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Seekers" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Shalaxi Hellbane" : {
            baseSize: "100mm",
            notes: "",
        },
        "Shardspeaker of Slaanesh" : {
            baseSize: "32mm",
            notes: "",
        },
        "Sigvald, Prince of Slaanesh" : {
            baseSize: "60mm",
            notes: "",
        },
        "Slaangor Fiendbloods" : {
            baseSize: "40mm",
            notes: "",
        },
        "Slickblade Seekers" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Syll'Esske, the Vengeful Allegiance" : {
            baseSize: "50mm",
            notes: "",
        },
        "Symbaresh Twinsouls" : {
            baseSize: "32mm",
            notes: "",
        },
        "Synessa, the Voice of Slaanesh" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "The Contorted Epitome" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "The Masque" : {
            baseSize: "32mm",
            notes: "",
        },
        "Viceleader, Herald of Slaanesh" : {
            baseSize: "25mm",
            notes: "",
        },
        "Wheels of Excruciation" : {
            baseSize: "Custom base",
            notes: "90 x 53mm",
        },
    }
}
export default Warscrolls