// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "hedonites of slaanesh",
    warscrolls: {
        "Blissbarb Archers" : {
            baseSize: "28.5mm [10], 25mm [1]",
            notes: "",
        },
        "Daemonettes" : {
            baseSize: "25mm",
            notes: "",
        },
        "Seekers" : {
            baseSize: "25 x 50mm",
            notes: "",
        },
        "Bladebringer, Herald on Exalted Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Bladebringer, Herald on Hellflayer" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Bladebringer, Herald on Seeker Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Contorted Epitome" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Dexcessa, the Talon of Slaanesh" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Infernal Enrapturess, Herald of Slaanesh" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Lord of Hubris" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord of Pain" : {
            baseSize: "40mm",
            notes: "",
        },
        "The Masque" : {
            baseSize: "32mm",
            notes: "",
        },
        "Shardspeaker of Slaanesh" : {
            baseSize: "32mm",
            notes: "",
        },
        "Sigvald, Prince of Slaanesh" : {
            baseSize: "60mm",
            notes: "",
        },
        "Syll'Esske, the Vengeful Allegiance" : {
            baseSize: "50mm",
            notes: "",
        },
        "Synessa, the Voice of Slaanesh" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Viceleader, Herald of Slaanesh" : {
            baseSize: "25mm",
            notes: "",
        },
        "Glutos Orscollion, Lord of Gluttony" : {
            baseSize: "170 x 105mm",
            notes: "",
        },
        "Keeper of Secrets" : {
            baseSize: "100mm",
            notes: "",
        },
        "Shalaxi Helbane" : {
            baseSize: "100mm",
            notes: "",
        },
        "Blissbarb Seekers" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "The Dread Pageant" : {
            baseSize: "32mm [1], 40mm [1], 25mm [2]",
            notes: "",
        },
        "Exalted Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Fiends" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Hellflayer" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Hellstriders with Claw-spears" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Hellstriders with Hellscourges" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Myrmidesh Painbringers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Seeker Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Slaangor Fiendbloods" : {
            baseSize: "40mm",
            notes: "",
        },
        "Slickblade Seekers" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Symbaresh Twinsouls" : {
            baseSize: "32mm",
            notes: "",
        },
        "Dreadful Visage" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Mesmerising Mirror" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Wheels of Excruciation" : {
            baseSize: "90 x 52mm ",
            notes: "(Official document says 'Use Model')",
        },
        "Fane of Slaanesh" : {
            baseSize: "Use model",
            notes: "",
        },
    }
}
export default Warscrolls