// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "idoneth deepkin",
    warscrolls: {
        "Akhelian Allopex" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Akhelian Ishlaen Guard" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Akhelian King" : {
            baseSize: "60mm",
            notes: "",
        },
        "Akhelian Leviadon" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Akhelian Morrsarr Guard" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Eidolon of Mathlann, Aspect of the Sea" : {
            baseSize: "100mm",
            notes: "",
        },
        "Eidolon of Mathlann, Aspect of the Storm" : {
            baseSize: "100mm",
            notes: "",
        },
        "Gloomtide Shipwreck" : {
            baseSize: "No base",
            notes: "",
        },
        "Isharann Soulrender" : {
            baseSize: "40mm",
            notes: "",
        },
        "Isharann Soulscryer" : {
            baseSize: "32mm",
            notes: "",
        },
        "Isharann Tidecaster" : {
            baseSize: "32mm",
            notes: "",
        },
        "Lotann, Warden of the Soul Ledgers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Namarti Reavers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Namarti Thralls" : {
            baseSize: "32mm",
            notes: "",
        },
        "Volturnos, High King of the Deep" : {
            baseSize: "60mm",
            notes: "",
        },
    }
}
export default Warscrolls