// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "kruleboyz",
    warscrolls: {
        "Beast-skewer Killbow" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Breaka-boss on Mirebrute Troggoth" : {
            baseSize: "80mm",
            notes: "",
        },
        "Gobsprakk, The Mouth of Mork" : {
            baseSize: "130mm",
            notes: "",
        },
        "Gutrippaz" : {
            baseSize: "32mm",
            notes: "",
        },
        "Hobgrot Slittaz" : {
            baseSize: "25mm",
            notes: "",
        },
        "Killaboss" : {
            baseSize: "40mm",
            notes: "",
        },
        "Killaboss on Corpse-rippa Vulcha" : {
            baseSize: "130mm",
            notes: "",
        },
        "Killaboss on Great Gnashtoof" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Man-skewer Boltboyz" : {
            baseSize: "32mm",
            notes: "",
        },
        "Marshcrawla Sloggoth" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Murknob with Belcha-banna" : {
            baseSize: "40mm",
            notes: "",
        },
        "Pot-grot" : {
            baseSize: "25mm",
            notes: "",
        },
        "Snatchaboss on Sludgeraker Beast" : {
            baseSize: "120 x 92mm",
            notes: "(listed as 'Large oval', I think this is right)",
        },
        "Stab-grot" : {
            baseSize: "25mm",
            notes: "",
        },
        "Swampcalla Shaman" : {
            baseSize: "40mm",
            notes: "",
        },
        "Swampboss Skumdrekk" : {
            baseSize: "120 x 92mm",
            notes: "(listed as 'Large oval', I think this is right)",
        },
    }
}
export default Warscrolls