// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "legions of nagash",
    warscrolls: {
        "Bat Swarms" : {
            baseSize: "50mm",
            notes: "",
        },
        "Vampire Lord on Nightmare Steed" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
    }
}
export default Warscrolls