// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "legions of azgorh",
    warscrolls: {
        "Bull Centaur Renders" : {
            baseSize: "90 x 52mm",
            notes: "(No longer in pdf)",
        },
        "Bull Centaur Taur’ruk" : {
            baseSize: "90 x 52mm",
            notes: "(No longer in pdf)",
        },
        "Daemonsmith" : {
            baseSize: "25mm",
            notes: "(No longer in pdf)",
        },
        "Deathshrieker Rocket Launcher" : {
            baseSize: "120 x 92mm",
            notes: "(No longer in pdf)",
        },
        "Drazhoath the Ashen" : {
            baseSize: "120 x 92mm",
            notes: "(No longer in pdf)",
        },
        "Dreadquake Mortar" : {
            baseSize: "170mm",
            notes: "(No longer in pdf)",
        },
        "Infernal Guard Battle Standard Bearer" : {
            baseSize: "25mm",
            notes: "(No longer in pdf)",
        },
        "Infernal Guard Castellan" : {
            baseSize: "25mm",
            notes: "(No longer in pdf)",
        },
        "Infernal Guard Fireglaives" : {
            baseSize: "25mm",
            notes: "(No longer in pdf)",
        },
        "Infernal Guard Ironsworn" : {
            baseSize: "25mm",
            notes: "(No longer in pdf)",
        },
        "Iron Daemon War Engine" : {
            baseSize: "120 x 92mm",
            notes: "(No longer in pdf)",
        },
        "K’Daai Fireborn" : {
            baseSize: "50mm",
            notes: "(No longer in pdf)",
        },
        "Magma Cannon" : {
            baseSize: "120 x 92mm",
            notes: "(No longer in pdf)",
        },
        "Shar’tor the Executioner" : {
            baseSize: "105 x 70mm",
            notes: "(No longer in pdf)",
        },
        "Skullcracker War Engine" : {
            baseSize: "120 x 92mm",
            notes: "(No longer in pdf)",
        },
    }
}
export default Warscrolls