// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "maggotkin of nurgle",
    warscrolls: {
        "Plaguebearers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Putrid Blightkings" : {
            baseSize: "40mm",
            notes: "",
        },
        "Epidemius, Tallyman of Nurgle" : {
            baseSize: "60mm",
            notes: "",
        },
        "Fecula Flyblown" : {
            baseSize: "40mm",
            notes: "",
        },
        "The Wurmspat" : {
            baseSize: "40mm",
            notes: "",
        },
        "Festus the Leechlord" : {
            baseSize: "40mm",
            notes: "",
        },
        "Gutrot Spume" : {
            baseSize: "40mm",
            notes: "",
        },
        "Harbinger of Decay" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Horticulous Slimux" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Lord of Afflictions" : {
            baseSize: "60mm",
            notes: "",
        },
        "Lord of Blights" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord of Plagues" : {
            baseSize: "40mm",
            notes: "",
        },
        "Poxbringer, Herald of Nurgle" : {
            baseSize: "32mm",
            notes: "",
        },
        "Rotbringer Sorcerer" : {
            baseSize: "32mm",
            notes: "",
        },
        "Rotbringer Sorcerer (Rot Coven)" : {
            baseSize: "32mm",
            notes: "",
        },
        "Sloppity Bilepiper, Herald of Nurgle" : {
            baseSize: "32mm",
            notes: "",
        },
        "Spoilpox Scrivener, Herald of Nurgle" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bloab Rotspawned" : {
            baseSize: "100mm",
            notes: "",
        },
        "The Glottkin" : {
            baseSize: "130mm",
            notes: "",
        },
        "Great Unclean One" : {
            baseSize: "130mm",
            notes: "",
        },
        "Morbidex Twiceborn" : {
            baseSize: "100mm",
            notes: "",
        },
        "Orghotts Daemonspew" : {
            baseSize: "100mm",
            notes: "",
        },
        "Rotigus" : {
            baseSize: "130mm",
            notes: "",
        },
        "Beasts of Nurgle" : {
            baseSize: "60mm",
            notes: "",
        },
        "Nurglings" : {
            baseSize: "40mm",
            notes: "",
        },
        "Plague Drones" : {
            baseSize: "60mm",
            notes: "",
        },
        "Pusgoyle Blightlords" : {
            baseSize: "60mm",
            notes: "",
        },
        "Rotmire Creed" : {
            baseSize: "32mm [2], 28.5mm [2], 25mm [6]",
            notes: "",
        },
        "Feculent Gnarlmaw" : {
            baseSize: "Use model",
            notes: "",
        },
    }
}
export default Warscrolls