// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "megagargant mercenaries",
    warscrolls: {
        "Big Drogg Fort-kicka" : {
            baseSize: "130mm",
            notes: "",
        },
        "Bundo Whalebiter" : {
            baseSize: "130mm",
            notes: "",
        },
        "Odo Godswallow" : {
            baseSize: "130mm",
            notes: "",
        },
        "One-eyed Grunnock" : {
            baseSize: "130mm",
            notes: "",
        },
    }
}
export default Warscrolls