// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "monsters of destruction",
    warscrolls: {
        "Basilisk" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Dread Maw" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Incarnate Elemental of Beasts" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Incarnate Elemental of Fire" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Magma Dragon" : {
            baseSize: "160mm",
            notes: "",
        },
        "Myrwyrm" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
    }
}
export default Warscrolls