// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "monsters of chaos",
    warscrolls: {
        "Chaos Siege Gargant" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Chaos War Mammoth" : {
            baseSize: "280 x 210mm",
            notes: "",
        },
        "Curs’d Ettin" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Gigantic Chaos Spawn" : {
            baseSize: "100mm",
            notes: "",
        },
        "Harpies" : {
            baseSize: "32mm",
            notes: "",
        },
        "Mutalith Vortex Beast" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Preyton" : {
            baseSize: "60mm",
            notes: "",
        },
        "Skin Wolves" : {
            baseSize: "60mm",
            notes: "",
        },
        "Slaughterbrute" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Warpfire Dragon" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
    }
}
export default Warscrolls