// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "nighthaunt",
    warscrolls: {
        "Chainrasps" : {
            baseSize: "25mm",
            notes: "",
        },
        "Grimghast Reapers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Hexwraiths" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Spirit Hosts" : {
            baseSize: "50mm",
            notes: "",
        },
        "Black Coach" : {
            baseSize: "170 x 105mm",
            notes: "",
        },
        "Awlrach the Drowner" : {
            baseSize: "80mm",
            notes: "",
        },
        "The Briar Queen" : {
            baseSize: "32mm",
            notes: "",
        },
        "Thorns of the Briar Queen" : {
            baseSize: "25mm",
            notes: "",
        },
        "Cairn Wraith" : {
            baseSize: "25mm",
            notes: "",
        },
        "Dreadblade Harrow" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Guardian of Souls" : {
            baseSize: "32mm",
            notes: "",
        },
        "Knight of Shrouds" : {
            baseSize: "32mm",
            notes: "",
        },
        "Knight of Shrouds on Ethereal Steed" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Krulghast Cruciator" : {
            baseSize: "40mm",
            notes: "",
        },
        "Kurdoss Valentian, the Craven King" : {
            baseSize: "60mm",
            notes: "",
        },
        "Lady Olynder, Mortarch of Grief" : {
            baseSize: "60mm",
            notes: "",
        },
        "Lord Executioner" : {
            baseSize: "40mm",
            notes: "",
        },
        "Reikenor the Grimhailer" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Scriptor Mortis" : {
            baseSize: "40mm",
            notes: "",
        },
        "Spirit Torment" : {
            baseSize: "40mm",
            notes: "",
        },
        "To m b B a n s h e e" : {
            baseSize: "25mm",
            notes: "",
        },
        "Nagash, Supreme Lord of the Undead" : {
            baseSize: "130mm",
            notes: "",
        },
        "Bladegheist Revenants" : {
            baseSize: "32mm",
            notes: "",
        },
        "Chainghasts" : {
            baseSize: "32mm",
            notes: "",
        },
        "Craventhrone Guard" : {
            baseSize: "32mm",
            notes: "",
        },
        "Dreadscythe Harridans" : {
            baseSize: "32mm",
            notes: "",
        },
        "Glaivewraith Stalkers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Myrmourn Banshees" : {
            baseSize: "32mm",
            notes: "",
        },
        "Mortalis Terminexus" : {
            baseSize: "50mm",
            notes: "",
        },
        "Shyish Reaper" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Vault of Souls" : {
            baseSize: "50mm",
            notes: "",
        },
    }
}
export default Warscrolls