// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "ogor mawtribes",
    warscrolls: {
        "Butcher" : {
            baseSize: "50mm",
            notes: "",
        },
        "Firebelly" : {
            baseSize: "50mm",
            notes: "",
        },
        "Frost Sabres" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Frostlord on Stonehorn" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Frostlord on Thundertusk" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Gorgers" : {
            baseSize: "50mm",
            notes: "",
        },
        "Gnoblar Scraplauncher" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Gnoblars" : {
            baseSize: "25mm",
            notes: "",
        },
        "Huskard on Stonehorn" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Huskard on Thundertusk" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Icebrow Hunter" : {
            baseSize: "50mm",
            notes: "",
        },
        "Icefall Yhetees" : {
            baseSize: "50mm",
            notes: "",
        },
        "Ironblaster" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Ironguts" : {
            baseSize: "40mm",
            notes: "",
        },
        "Leadbelchers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Maneaters" : {
            baseSize: "50mm",
            notes: "",
        },
        "Mournfang Pack" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Ogor Gluttons" : {
            baseSize: "40mm",
            notes: "",
        },
        "Slaughtermaster" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Stonehorn Beastriders" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Thundertusk Beastriders" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Tyrant" : {
            baseSize: "50mm",
            notes: "",
        },
    }
}
export default Warscrolls