// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "order draconis",
    warscrolls: {
        "Dragon Noble" : {
            baseSize: "25mm",
            notes: "",
        },
        "Dragon Noble on Steed" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Dragonlord" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Dragon Blades" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
    }
}
export default Warscrolls