// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "order",
    warscrolls: {
        "Gotrek Gurnisson" : {
            baseSize: "32mm",
            notes: "",
        },
    }
}
export default Warscrolls