// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "skaven",
    warscrolls: {
        "Arch-Warlock" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bell of Doom" : {
            baseSize: "40mm",
            notes: "",
        },
        "Brood Horror" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Clanrats" : {
            baseSize: "25mm",
            notes: "",
        },
        "Clawlord" : {
            baseSize: "32mm",
            notes: "",
        },
        "Deathmaster" : {
            baseSize: "32mm",
            notes: "",
        },
        "Doom-Flayer" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Doomwheel" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Giant Rats" : {
            baseSize: "25mm",
            notes: "",
        },
        "Grey Seer" : {
            baseSize: "32mm",
            notes: "",
        },
        "Grey Seer on Screaming Bell" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Gutter Runners" : {
            baseSize: "25mm",
            notes: "",
        },
        "Hell Pit Abomination" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Lord Skreech Verminking" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Master Moulder" : {
            baseSize: "32mm",
            notes: "",
        },
        "Night Runners" : {
            baseSize: "25mm",
            notes: "",
        },
        "Packmasters" : {
            baseSize: "25mm",
            notes: "",
        },
        "Plague Censer Bearers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Plague Monks" : {
            baseSize: "25mm",
            notes: "",
        },
        "Plague Priest" : {
            baseSize: "32mm",
            notes: "",
        },
        "Plague Priest on Plague Furnace" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Plagueclaw" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Rat Ogors" : {
            baseSize: "50mm",
            notes: "",
        },
        "Rat Swarms" : {
            baseSize: "50mm",
            notes: "",
        },
        "Ratling Gun" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Skaven Warlord on Brood Horror" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Skaven Wolf Rats" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Skritch Spiteclaw" : {
            baseSize: "32mm",
            notes: "",
        },
        "Skryre Acolytes" : {
            baseSize: "32mm",
            notes: "",
        },
        "Spiteclaw’s Swarm" : {
            baseSize: "25mm",
            notes: "",
        },
        "Stormfiends" : {
            baseSize: "60mm",
            notes: "",
        },
        "Stormvermin" : {
            baseSize: "25mm",
            notes: "",
        },
        "Thanquol on Boneripper" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Verminlord Corruptor" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Verminlord Deceiver" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Verminlord Warbringer" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Verminlord Warpseer" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Vermintide" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Warlock Bombardier" : {
            baseSize: "32mm",
            notes: "",
        },
        "Warlock Engineer" : {
            baseSize: "32mm",
            notes: "",
        },
        "Warp Lightning Cannon" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Warp Lightning Vortex" : {
            baseSize: "40mm",
            notes: "",
        },
        "Warp-Grinder" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Warpfire Thrower" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Warpgnaw Verminlord" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Warplock Jezzails" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
    }
}
export default Warscrolls