// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "slaves to darkness",
    warscrolls: {
        "Chaos Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Chaos Knights" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Chaos Legionnaires" : {
            baseSize: "32mm [5], 28.5mm [3]",
            notes: "",
        },
        "Chaos Marauder Horsemen" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Chaos Marauders" : {
            baseSize: "25mm",
            notes: "",
        },
        "Chaos Warriors" : {
            baseSize: "32mm",
            notes: "",
        },
        "Corvus Cabal" : {
            baseSize: "40mm [1], 28.5mm [3], 25mm [5]",
            notes: "",
        },
        "Cypher Lords" : {
            baseSize: "32mm [1], 28.5mm [4], 25mm [3]",
            notes: "",
        },
        "Darkoath Savagers" : {
            baseSize: "32mm [3], 28.5mm [7]",
            notes: "",
        },
        "Horns of Hashut" : {
            baseSize: "32mm [3], 28.5mm [4], 25mm [3]",
            notes: "",
        },
        "Iron Golem" : {
            baseSize: "40mm [1], 32mm [3], 28.5mm [4]",
            notes: "",
        },
        "Scions of the Flame" : {
            baseSize: "32mm [3], 28.5mm [3], 25mm [2]",
            notes: "",
        },
        "Spire Tyrants" : {
            baseSize: "32mm [3], 28.5mm [4], 25mm [2]",
            notes: "",
        },
        "Splintered Fang" : {
            baseSize: "32mm [3], 28.5mm [2], 25mm [5]",
            notes: "",
        },
        "Tarantulos Brood" : {
            baseSize: "32mm [1], 28.5mm [2], 25mm [10]",
            notes: "",
        },
        "The Unmade" : {
            baseSize: "40mm [1], 32mm [1], 28.5mm [3], 25mm [4]",
            notes: "",
        },
        "Untamed Beasts" : {
            baseSize: "40mm [1], 32mm [3], 28.5mm [2], 25mm [3]",
            notes: "",
        },
        "Chaos Warshrine" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Mutalith Vortex Beast" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Slaughterbrute" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Soul Grinder" : {
            baseSize: "160mm",
            notes: "",
        },
        "Centaurion Marshal" : {
            baseSize: "80mm",
            notes: "",
        },
        "Chaos Lord" : {
            baseSize: "40mm",
            notes: "",
        },
        "Chaos Lord on Daemonic Mount" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Chaos Lord on Karkadrak" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Chaos Sorcerer Lord" : {
            baseSize: "32mm",
            notes: "",
        },
        "Daemon Prince" : {
            baseSize: "60mm",
            notes: "",
        },
        "Darkoath Chieftain" : {
            baseSize: "32mm",
            notes: "",
        },
        "Darkoath Warqueen" : {
            baseSize: "32mm",
            notes: "",
        },
        "Eternus, Blade of the First Prince" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Exalted Hero of Chaos" : {
            baseSize: "40mm",
            notes: "",
        },
        "Ogroid Myrmidon" : {
            baseSize: "50mm",
            notes: "",
        },
        "Sarrakkar Blackwing" : {
            baseSize: "32mm",
            notes: "",
        },
        "The Gnarlspirit Pack" : {
            baseSize: "32mm",
            notes: "",
        },
        "Gaunt Summoner" : {
            baseSize: "40mm",
            notes: "",
        },
        "Gaunt Summoner on Disc of Tzeentch" : {
            baseSize: "40mm",
            notes: "",
        },
        "Theddra Skull-Scryer" : {
            baseSize: "32mm",
            notes: "",
        },
        "Godsworn Hunt" : {
            baseSize: "32mm [4], 25mm [1]",
            notes: "",
        },
        "Zarshia Bittersoul" : {
            baseSize: "32mm",
            notes: "",
        },
        "Khagra's Ravagers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Archaon the Everchosen" : {
            baseSize: "160mm",
            notes: "",
        },
        "Be'lakor, the Dark Master" : {
            baseSize: "100mm",
            notes: "",
        },
        "Chaos Lord on Manticore" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Chaos Sorcerer Lord on Manticore" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Chaos Chosen" : {
            baseSize: "40mm",
            notes: "",
        },
        "Fomoroid Crusher" : {
            baseSize: "60mm",
            notes: "",
        },
        "Furies" : {
            baseSize: "32mm",
            notes: "",
        },
        "Gorebeast Chariots" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Mindstealer Sphiranx" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Ogroid Theridons" : {
            baseSize: "50mm",
            notes: "",
        },
        "Raptoryx" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Chaos Spawn" : {
            baseSize: "50mm",
            notes: "",
        },
        "Varanguard" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Darkfire Daemonrift" : {
            baseSize: "Use model",
            notes: "",
        },
        "Eightfold Doom-Sigil" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Realmscourge Rupture" : {
            baseSize: "Use model",
            notes: "",
        },
    }
}
export default Warscrolls