// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "sons of behemat",
    warscrolls: {
        "Mancrusher Gargant" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Mancrusher Mob" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Beast-smasher Mega-Gargant" : {
            baseSize: "130mm",
            notes: "",
        },
        "Gatebreaker Mega-Gargant" : {
            baseSize: "130mm",
            notes: "",
        },
        "King Brodd" : {
            baseSize: "130mm",
            notes: "",
        },
        "Kraken-eater Mega-Gargant" : {
            baseSize: "130mm",
            notes: "",
        },
        "Warstomper Mega-Gargant" : {
            baseSize: "130mm",
            notes: "",
        },
        "Kragnos, the End of Empires" : {
            baseSize: "130mm",
            notes: "",
        },
    }
}
export default Warscrolls