// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "soulblight gravelords",
    warscrolls: {
        "Deadwalker Zombies" : {
            baseSize: "25mm",
            notes: "",
        },
        "Deathrattle Skeletons" : {
            baseSize: "25mm",
            notes: "",
        },
        "Dire Wolves" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Mortis Engine" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Te r r o r g h e i s t" : {
            baseSize: "130mm",
            notes: "",
        },
        "Zombie Dragon" : {
            baseSize: "130mm",
            notes: "",
        },
        "Belladamma Volga, First of the Vyrkos" : {
            baseSize: "60mm",
            notes: "",
        },
        "Cado Ezechiar, the Hollow King" : {
            baseSize: "40mm",
            notes: "",
        },
        "Deintalos the Exile" : {
            baseSize: "28.5mm",
            notes: "",
        },
        "The Exiled Dead" : {
            baseSize: "25mm",
            notes: "",
        },
        "Gorslav the Gravekeeper" : {
            baseSize: "40mm",
            notes: "",
        },
        "Ivya Volga, the Outcast" : {
            baseSize: "40mm",
            notes: "",
        },
        "King Morlak Velmorn" : {
            baseSize: "32mm",
            notes: "",
        },
        "The Sons of Velmorn" : {
            baseSize: "40mm [1], 25mm [3]",
            notes: "",
        },
        "Kritza, the Rat Prince" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Lady Annika, the Thirsting Blade" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Lauka Vai, Mother of Nightmares" : {
            baseSize: "80mm",
            notes: "",
        },
        "Necromancer" : {
            baseSize: "32mm",
            notes: "",
        },
        "Prince Duvalle" : {
            baseSize: "32mm",
            notes: "",
        },
        "The Crimson Court" : {
            baseSize: "32mm",
            notes: "",
        },
        "Radukar the Beast" : {
            baseSize: "60mm",
            notes: "",
        },
        "Radukar the Wolf" : {
            baseSize: "40mm",
            notes: "",
        },
        "Torgillius the Chamberlain" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vampire Lord" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vengorian Lord" : {
            baseSize: "80mm",
            notes: "",
        },
        "Watch Captain Halgrim" : {
            baseSize: "32mm",
            notes: "",
        },
        "Wight King" : {
            baseSize: "32mm",
            notes: "",
        },
        "Wight King on Skeletal Steed" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Bloodseeker Palanquin" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Coven Throne" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Mannfred von Carstein, Mortarch of Night" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Nagash, Supreme Lord of the Undead" : {
            baseSize: "130mm",
            notes: "",
        },
        "Neferata, Mortarch of Blood" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Prince Vhordrai" : {
            baseSize: "130mm",
            notes: "",
        },
        "Vampire Lord on Zombie Dragon" : {
            baseSize: "130mm",
            notes: "",
        },
        "Askurgan Trueblades" : {
            baseSize: "40mm [1], 32mm [4], 28mm [3]",
            notes: "",
        },
        "Black Knights" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Blood Knights" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Corpse Cart" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Fell Bats" : {
            baseSize: "40mm",
            notes: "",
        },
        "Grave Guard" : {
            baseSize: "25mm",
            notes: "",
        },
        "Kosargi Nightguard" : {
            baseSize: "40mm",
            notes: "",
        },
        "The Sepulchral Guard" : {
            baseSize: "25mm",
            notes: "",
        },
        "Vargheists" : {
            baseSize: "50mm",
            notes: "",
        },
        "Va r gs k y r" : {
            baseSize: "50mm",
            notes: "",
        },
        "Vyrkos Blood-born" : {
            baseSize: "32mm",
            notes: "",
        },
    }
}
export default Warscrolls