// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "stormcast eternals",
    warscrolls: {
        "Celestar Ballista" : {
            baseSize: "60mm [1], 40mm [2]",
            notes: "",
        },
        "Judicators with Boltstorm Crossbows" : {
            baseSize: "40mm",
            notes: "",
        },
        "Judicators with Skybolt Bows" : {
            baseSize: "40mm",
            notes: "",
        },
        "Liberators" : {
            baseSize: "40mm",
            notes: "",
        },
        "Sequitors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vanquishers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vindictors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Astreia Solbright" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Aventis Firestrike, Magister of Hammerhal" : {
            baseSize: "100mm",
            notes: "",
        },
        "Averon Stormsire" : {
            baseSize: "40mm",
            notes: "",
        },
        "Stormsire's Cursebreakers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Celestant-Prime, Hammer of Sigmar" : {
            baseSize: "100mm",
            notes: "",
        },
        "Gardus Steel Soul" : {
            baseSize: "50mm",
            notes: "",
        },
        "Gavriel Sureheart" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Arcanum" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Azyros" : {
            baseSize: "50mm",
            notes: "",
        },
        "Knight-Draconis" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Knight-Heraldor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Incantor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Judicator with Gryph-hounds" : {
            baseSize: "90 x 52mm [1], 40mm [2]",
            notes: "",
        },
        "Knight-Questor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Relictor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Venator" : {
            baseSize: "50mm",
            notes: "",
        },
        "Knight-Vexillor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Vexillor with Banner of Apotheosis" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Zephyros" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Aquilor" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Lord-Arcanum" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Arcanum on Celestial Dracoline" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Lord-Arcanum on Gryph-charger" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Lord-Arcanum on Tauralon" : {
            baseSize: "100mm",
            notes: "",
        },
        "Lord-Castellant" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Celestant" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Celestant on Dracoth" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Lord-Commander Bastian Carthalos" : {
            baseSize: "50mm",
            notes: "",
        },
        "Lord-Exorcist" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Imperatant" : {
            baseSize: "40mm [1], 32mm [1]",
            notes: "",
        },
        "Lord-Ordinator" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Relictor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Veritant" : {
            baseSize: "40mm",
            notes: "",
        },
        "Neave Blacktalon" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vandus Hammerhand" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Yndrasta, the Celestial Spear" : {
            baseSize: "60mm",
            notes: "",
        },
        "Drakesworn Templar" : {
            baseSize: "170 x 105mm",
            notes: "",
        },
        "Karazai the Scarred" : {
            baseSize: "160mm",
            notes: "",
        },
        "Krondys, Son of Dracothion" : {
            baseSize: "160mm",
            notes: "",
        },
        "Lord-Celestant on Stardrake" : {
            baseSize: "170 x 105mm",
            notes: "",
        },
        "Aetherwings" : {
            baseSize: "32mm",
            notes: "",
        },
        "Annihilators" : {
            baseSize: "40mm",
            notes: "",
        },
        "Annihilators with Meteoric Grandhammers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Castigators" : {
            baseSize: "40mm",
            notes: "",
        },
        "Decimators" : {
            baseSize: "40mm",
            notes: "",
        },
        "Domitan's Stormcoven" : {
            baseSize: "40mm [3]",
            notes: "",
        },
        "Dracothian Guard Concussors" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Dracothian Guard Desolators" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Dracothian Guard Fulminators" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Dracothian Guard Tempestors" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Evocators" : {
            baseSize: "40mm",
            notes: "",
        },
        "Evocators on Celestial Dracolines" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "The Farstriders" : {
            baseSize: "40mm",
            notes: "",
        },
        "Gryph-hounds" : {
            baseSize: "40mm",
            notes: "",
        },
        "Praetors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Prosecutors with Celestial Hammers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Prosecutors with Stormcall Javelins" : {
            baseSize: "40mm",
            notes: "",
        },
        "Protectors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Questor Soulsworn" : {
            baseSize: "40mm",
            notes: "",
        },
        "Retributors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Steelheart's Champions" : {
            baseSize: "40mm",
            notes: "",
        },
        "Stormdrake Guard" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Stormstrike Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Vanguard-Hunters" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vanguard-Palladors" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Vanguard-Raptors with Hurricane Crossbows" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vanguard-Raptors with Longstrike Crossbows" : {
            baseSize: "60 x 35mm [2], 40mm [1]",
            notes: "",
        },
        "Vigilors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Xandire's Truthseekers" : {
            baseSize: "40mm [3], 25mm [1]",
            notes: "",
        },
        "Celestian Vortex" : {
            baseSize: "65mm",
            notes: "",
        },
        "Dais Arcanum" : {
            baseSize: "50mm",
            notes: "",
        },
        "Everblaze Comet" : {
            baseSize: "65mm",
            notes: "",
        },
        "Ionus Cryptborn" : {
            baseSize: "100mm",
            notes: "",
        },
        "Neave's Companions" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lorai, Child of the Abyss" : {
            baseSize: "40mm",
            notes: "",
        },
    }
}
export default Warscrolls