// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "stormcast eternals",
    warscrolls: {
        "Aetherwings" : {
            baseSize: "32mm",
            notes: "",
        },
        "Annihilators" : {
            baseSize: "40mm",
            notes: "",
        },
        "Astreia Solbright" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Aventis Firestrike, Magister of Hammerhal" : {
            baseSize: "100mm",
            notes: "",
        },
        "Castigators" : {
            baseSize: "40mm",
            notes: "",
        },
        "Celestant-Prime, Hammer of Sigmar" : {
            baseSize: "100mm",
            notes: "",
        },
        "Celestar Ballista" : {
            baseSize: "60mm",
            notes: "",
        },
        "Celestar Ballista Crew" : {
            baseSize: "40mm",
            notes: "",
        },
        "Celestian Vortex" : {
            baseSize: "65mm",
            notes: "",
        },
        "Dais Arcanum" : {
            baseSize: "50mm",
            notes: "",
        },
        "Dracothian Guard Concussors" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Dracothian Guard Desolators" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Dracothian Guard Fulminators" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Dracothian Guard Tempestors" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Drakesworn Templar" : {
            baseSize: "170 x 105mm",
            notes: "",
        },
        "Everblaze Comet" : {
            baseSize: "65mm",
            notes: "",
        },
        "Evocators" : {
            baseSize: "40mm",
            notes: "",
        },
        "Evocators on Dracolines" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Gavriel Sureheart" : {
            baseSize: "40mm",
            notes: "",
        },
        "Gryph-hounds" : {
            baseSize: "40mm",
            notes: "(some heroes have small ones on 32mm)",
        },
        "Judicators" : {
            baseSize: "40mm",
            notes: "",
        },
        "Karazai the Scarred" : {
            baseSize: "160mm",
            notes: "",
        },
        "Knight-Arcanum" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Azyros" : {
            baseSize: "50mm",
            notes: "",
        },
        "Knight-Draconis" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Knight-Heraldor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Incantor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Judicator" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Knight-Questor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Relictor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Venator" : {
            baseSize: "50mm",
            notes: "",
        },
        "Knight-Vexillor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Knight-Zephyros" : {
            baseSize: "40mm",
            notes: "",
        },
        "Krondys, Son of Dracothion" : {
            baseSize: "160mm",
            notes: "",
        },
        "Liberators" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Aquilor" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Lord-Arcanum" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Arcanum on Dracoline" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Lord-Arcanum on Gryph-charger" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Lord-Arcanum on Tauralon" : {
            baseSize: "100mm",
            notes: "",
        },
        "Lord-Castellant" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Celestant" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Celestant on Dracoth" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Lord-Celestant on Stardrake" : {
            baseSize: "170 x 105mm",
            notes: "",
        },
        "Lord-Commander Bastian Carthalos" : {
            baseSize: "50mm",
            notes: "",
        },
        "Lord-Exorcist" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Imperatant" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Ordinator Vorrus Starstrike" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Relictor" : {
            baseSize: "40mm",
            notes: "",
        },
        "Lord-Veritant" : {
            baseSize: "40mm",
            notes: "",
        },
        "Neave Blacktalon" : {
            baseSize: "40mm",
            notes: "",
        },
        "Paladin Decimators" : {
            baseSize: "40mm",
            notes: "",
        },
        "Paladin Protectors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Paladin Retributors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Praetors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Prosecutors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Raptor-Prime with Longstrike Crossbow" : {
            baseSize: "40mm",
            notes: "",
        },
        "Sequitors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Steelheart’s Champions" : {
            baseSize: "40mm",
            notes: "",
        },
        "Stormdrake Guard" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Stormstrike Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "The Farstriders" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vandus Hammerhand" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Vanguard-Hunters" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vanguard-Palladors" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Vanguard-Raptors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vanguard-Raptors with Longstrike Crossbows" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Vanquishers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vigilors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vindictors" : {
            baseSize: "40mm",
            notes: "",
        },
        "Yndrasta, the Celestial Spear" : {
            baseSize: "65mm",
            notes: "",
        },
    }
}
export default Warscrolls