// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "sylvaneth",
    warscrolls: {
        "Dryads" : {
            baseSize: "32mm",
            notes: "",
        },
        "Tree-Revena nts" : {
            baseSize: "32mm",
            notes: "",
        },
        "Treelord" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Arch-Revenant" : {
            baseSize: "40mm",
            notes: "",
        },
        "Branchwych" : {
            baseSize: "32mm",
            notes: "",
        },
        "Drycha Hamadreth" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "The Lady of Vines" : {
            baseSize: "80mm",
            notes: "",
        },
        "Warsong Revenant" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Ylthari" : {
            baseSize: "32mm",
            notes: "",
        },
        "Ylthari's Guardians" : {
            baseSize: "32mm",
            notes: "",
        },
        "Alarielle the Everqueen" : {
            baseSize: "160mm",
            notes: "",
        },
        "Spirit of Durthu" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Treelord Ancient" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Gossamid Archers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Kurnoth Hunters with Kurnoth Greatbows" : {
            baseSize: "50mm",
            notes: "",
        },
        "Kurnoth Hunters with Kurnoth Greatswords" : {
            baseSize: "50mm",
            notes: "",
        },
        "Kurnoth Hunters with Kurnoth Scythes" : {
            baseSize: "50mm",
            notes: "",
        },
        "Revenant Seekers" : {
            baseSize: "60mm",
            notes: "",
        },
        "Skaeth's Wild Hunt" : {
            baseSize: "50 x 25mm [1], 32mm [3], 25mm [1]",
            notes: "",
        },
        "Spite-Revenants" : {
            baseSize: "32mm",
            notes: "",
        },
        "Spiterider Lancers" : {
            baseSize: "60mm",
            notes: "",
        },
        "Gladewyrm" : {
            baseSize: "Use model",
            notes: "",
        },
        "Spiteswarm Hive" : {
            baseSize: "50mm",
            notes: "",
        },
        "Vengeful Skullroot" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Awakened Wyldwood" : {
            baseSize: "Use model",
            notes: "",
        },
    }
}
export default Warscrolls