// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "tamurkhans horde",
    warscrolls: {
        "Bile Troggoths" : {
            baseSize: "60mm",
            notes: "",
        },
        "Daemon Pox Riders of Nurgle" : {
            baseSize: "60mm",
            notes: "",
        },
        "Daemon Plague Toads of Nurgle" : {
            baseSize: "60mm",
            notes: "",
        },
        "Kazyk the Befouled" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Plague Ogors" : {
            baseSize: "60mm",
            notes: "",
        },
        "Tamurkhan the Maggot Lord" : {
            baseSize: "280 x 210mm",
            notes: "",
        },
    }
}
export default Warscrolls