// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "warcry",
    warscrolls: {
        "Horns of Hashut" : {
            baseSize: "Mixed",
            notes: "(3x32mm, 4x28mm, 3x25mm)",
        },
        "Rotmire Creed" : {
            baseSize: "Mixed",
            notes: "(2x32mm, 2x28mm, 6x25mm)",
        },
    }
}
export default Warscrolls