// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls, TWarscrolls } from "./types";
import { tagAndCombine } from "../utils/data";

import Beasts_Of_ChaosWarscrolls from "./data/beasts_of_chaos"
import Blades_Of_KhorneWarscrolls from "./data/blades_of_khorne"
import Cities_Of_SigmarWarscrolls from "./data/cities_of_sigmar"
import Cursed_CityWarscrolls from "./data/cursed_city"
import Daughters_Of_KhaineWarscrolls from "./data/daughters_of_khaine"
import Disciples_Of_TzeentchWarscrolls from "./data/disciples_of_tzeentch"
import Eldritch_CouncilWarscrolls from "./data/eldritch_council"
import Endless_SpellsWarscrolls from "./data/endless_spells"
import FimirWarscrolls from "./data/fimir"
import Flesheater_CourtsWarscrolls from "./data/flesheater_courts"
import FyreslayersWarscrolls from "./data/fyreslayers"
import Gloomspite_GitzWarscrolls from "./data/gloomspite_gitz"
import Gnomad_FeastmastersWarscrolls from "./data/gnomad_feastmasters"
import GreenskinzWarscrolls from "./data/greenskinz"
import Hedonites_Of_SlaaneshWarscrolls from "./data/hedonites_of_slaanesh"
import Idoneth_DeepkinWarscrolls from "./data/idoneth_deepkin"
import IncarnatesWarscrolls from "./data/incarnates"
import Kharadron_OverlordsWarscrolls from "./data/kharadron_overlords"
import Legions_Of_AzgorhWarscrolls from "./data/legions_of_azgorh"
import Lion_RangersWarscrolls from "./data/lion_rangers"
import Lumineth_RealmlordsWarscrolls from "./data/lumineth_realmlords"
import Maggotkin_Of_NurgleWarscrolls from "./data/maggotkin_of_nurgle"
import Megagargant_MercenariesWarscrolls from "./data/megagargant_mercenaries"
import NighthauntWarscrolls from "./data/nighthaunt"
import Ogor_MawtribesWarscrolls from "./data/ogor_mawtribes"
import OrderWarscrolls from "./data/order"
import Order_DraconisWarscrolls from "./data/order_draconis"
import Orruk_WarclansWarscrolls from "./data/orruk_warclans"
import Ossiarch_BonereapersWarscrolls from "./data/ossiarch_bonereapers"
import SeraphonWarscrolls from "./data/seraphon"
import SkavenWarscrolls from "./data/skaven"
import Slaves_To_DarknessWarscrolls from "./data/slaves_to_darkness"
import Sons_Of_BehematWarscrolls from "./data/sons_of_behemat"
import Soulblight_GravelordsWarscrolls from "./data/soulblight_gravelords"
import Stormcast_EternalsWarscrolls from "./data/stormcast_eternals"
import SylvanethWarscrolls from "./data/sylvaneth"
import Tamurkhans_HordeWarscrolls from "./data/tamurkhans_horde"

export const UntaggedWarscrolls: TFactionWarscrolls[] = [
    Beasts_Of_ChaosWarscrolls,
    Blades_Of_KhorneWarscrolls,
    Cities_Of_SigmarWarscrolls,
    Cursed_CityWarscrolls,
    Daughters_Of_KhaineWarscrolls,
    Disciples_Of_TzeentchWarscrolls,
    Eldritch_CouncilWarscrolls,
    Endless_SpellsWarscrolls,
    FimirWarscrolls,
    Flesheater_CourtsWarscrolls,
    FyreslayersWarscrolls,
    Gloomspite_GitzWarscrolls,
    Gnomad_FeastmastersWarscrolls,
    GreenskinzWarscrolls,
    Hedonites_Of_SlaaneshWarscrolls,
    Idoneth_DeepkinWarscrolls,
    IncarnatesWarscrolls,
    Kharadron_OverlordsWarscrolls,
    Legions_Of_AzgorhWarscrolls,
    Lion_RangersWarscrolls,
    Lumineth_RealmlordsWarscrolls,
    Maggotkin_Of_NurgleWarscrolls,
    Megagargant_MercenariesWarscrolls,
    NighthauntWarscrolls,
    Ogor_MawtribesWarscrolls,
    OrderWarscrolls,
    Order_DraconisWarscrolls,
    Orruk_WarclansWarscrolls,
    Ossiarch_BonereapersWarscrolls,
    SeraphonWarscrolls,
    SkavenWarscrolls,
    Slaves_To_DarknessWarscrolls,
    Sons_Of_BehematWarscrolls,
    Soulblight_GravelordsWarscrolls,
    Stormcast_EternalsWarscrolls,
    SylvanethWarscrolls,
    Tamurkhans_HordeWarscrolls,
]

let cachedWarscrolls: TWarscrolls

export const getWarscrolls = () :TWarscrolls => {
    if (cachedWarscrolls === undefined) {
        cachedWarscrolls = tagAndCombine(UntaggedWarscrolls)
    }
    return cachedWarscrolls
}