// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "beasts of chaos",
    warscrolls: {
        "Beastlord" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bestigors" : {
            baseSize: "32mm",
            notes: "",
        },
        "Bullgors" : {
            baseSize: "50mm",
            notes: "",
        },
        "Centigors" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Chaos Gargant" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Chaos Warhounds" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Chimera" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Cockatrice" : {
            baseSize: "60mm",
            notes: "",
        },
        "Cygor" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Doomblast Dirgehorn" : {
            baseSize: "40mm",
            notes: "",
        },
        "Doombull" : {
            baseSize: "50mm",
            notes: "",
        },
        "Dragon Ogor Shaggoth" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Dragon Ogors" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Ghorgon" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Gors" : {
            baseSize: "32mm",
            notes: "",
        },
        "Great Bray-Shaman" : {
            baseSize: "32mm",
            notes: "",
        },
        "Jabberslythe" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Ravening Direflock" : {
            baseSize: "40mm",
            notes: "",
        },
        "Razorgors" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Tuskgor Chariots" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Ungor Raiders" : {
            baseSize: "25mm",
            notes: "",
        },
        "Ungors" : {
            baseSize: "25mm",
            notes: "",
        },
        "Wildfire Taurus" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
    }
}
export default Warscrolls