// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "daemons of chaos",
    warscrolls: {
        "Be’lakor, Chaos Daemon Prince" : {
            baseSize: "100mm",
            notes: "(old one was 60mm)",
        },
        "Daemon Prince" : {
            baseSize: "60mm",
            notes: "",
        },
        "Furies" : {
            baseSize: "25mm",
            notes: "(Warcry ones are on 32mm)",
        },
        "Soul Grinder" : {
            baseSize: "160mm",
            notes: "",
        },
    }
}
export default Warscrolls