// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "daughters of khaine",
    warscrolls: {
        "Avatar of Khaine" : {
            baseSize: "40mm",
            notes: "",
        },
        "Blood Sisters" : {
            baseSize: "40mm",
            notes: "",
        },
        "Blood Stalkers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bloodwrack Medusae" : {
            baseSize: "40mm",
            notes: "",
        },
        "Bloodwrack Shrine" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Doomfire Warlocks" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Hag Queen" : {
            baseSize: "25mm",
            notes: "",
        },
        "Hag Queen on Cauldron of Blood" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Khinerai Heartrenders" : {
            baseSize: "40mm",
            notes: "",
        },
        "Khinerai Lifetakers" : {
            baseSize: "40mm",
            notes: "",
        },
        "Morathi, High Oracle of Khaine" : {
            baseSize: "40mm",
            notes: "",
        },
        "Morathi, the Shadow Queen" : {
            baseSize: "100mm",
            notes: "",
        },
        "Sisters of Slaughter" : {
            baseSize: "25mm",
            notes: "",
        },
        "Slaughter Queen" : {
            baseSize: "25mm",
            notes: "",
        },
        "Slaughter Queen on Cauldron of Blood" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Witch Aelves" : {
            baseSize: "25mm",
            notes: "",
        },
    }
}
export default Warscrolls