// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "destruction",
    warscrolls: {
        "Kragnos The End of Empires" : {
            baseSize: "130mm",
            notes: "",
        },
    }
}
export default Warscrolls