// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "eldritch council",
    warscrolls: {
        "Archmage" : {
            baseSize: "25mm",
            notes: "",
        },
        "Archmage on Steed" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Archmage on Dragon" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Drakeseer" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Loremaster" : {
            baseSize: "25mm",
            notes: "",
        },
        "Swordmasters" : {
            baseSize: "25mm",
            notes: "",
        },
    }
}
export default Warscrolls