// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "hedonites of slaanesh",
    warscrolls: {
        "Chaos Lord of Slaanesh" : {
            baseSize: "32mm",
            notes: "",
        },
        "Daemonettes of Slaanesh" : {
            baseSize: "25mm",
            notes: "",
        },
        "Dreadful Visage" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Exalted Greater Daemon of Slaanesh" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Exalted Seekers Chariots of Slaanesh" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Fiends" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Hellflayers of Slaanesh" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Hellstriders of Slaanesh" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Herald of Slaanesh" : {
            baseSize: "25mm",
            notes: "",
        },
        "Herald of Slaanesh on Exalted Seeker Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Herald of Slaanesh on Seeker Chariot" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Infernal Enrapturess" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Keeper of Secrets" : {
            baseSize: "100mm",
            notes: "",
        },
        "Lord of Slaanesh on Daemonic Mount" : {
            baseSize: "60mm",
            notes: "",
        },
        "Mesmerising Mirror" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Seeker Chariots of Slaanesh" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Seekers of Slaanesh" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "The Masque of Slaanesh" : {
            baseSize: "32mm",
            notes: "",
        },
        "Wheels of Excruciation" : {
            baseSize: "Custom base",
            notes: "90 x 53mm",
        },
    }
}
export default Warscrolls