// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "kharadron overlords",
    warscrolls: {
        "Aether-Khemist" : {
            baseSize: "32mm",
            notes: "",
        },
        "Aetheric Navigator" : {
            baseSize: "32mm",
            notes: "",
        },
        "Arkanaut Admiral" : {
            baseSize: "32mm",
            notes: "",
        },
        "Arkanaut Company" : {
            baseSize: "25mm",
            notes: "",
        },
        "Arkanaut Frigate" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Arkanaut Ironclad" : {
            baseSize: "170 x 105mm",
            notes: "",
        },
        "Brokk Grungsson, Lord-Magnate of Barak-Nar" : {
            baseSize: "50mm",
            notes: "",
        },
        "Endrinmaster" : {
            baseSize: "32mm",
            notes: "",
        },
        "Endrinriggers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Grundstok Gunhauler" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Grundstok Thunderers" : {
            baseSize: "32mm",
            notes: "",
        },
        "Skywardens" : {
            baseSize: "32mm",
            notes: "",
        },
    }
}
export default Warscrolls