// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "kruleboyz",
    warscrolls: {
        "Gutrippaz" : {
            baseSize: "32mm",
            notes: "",
        },
        "Hobgrot Slittaz" : {
            baseSize: "25mm",
            notes: "",
        },
        "Killaboss" : {
            baseSize: "40mm",
            notes: "",
        },
        "Killaboss on Great Gnashtoof" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Man-skewer Boltboyz" : {
            baseSize: "32mm",
            notes: "",
        },
        "Murknob with Belcha-banna" : {
            baseSize: "40mm",
            notes: "",
        },
        "Pot-grot" : {
            baseSize: "25mm",
            notes: "",
        },
        "Stab-grot" : {
            baseSize: "25mm",
            notes: "",
        },
        "Swampcalla Shaman" : {
            baseSize: "40mm",
            notes: "",
        },
    }
}
export default Warscrolls