// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "legions of nagash",
    warscrolls: {
        "Arkhan the Black, Mortarch of Sacrament" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Bat Swarms" : {
            baseSize: "50mm",
            notes: "",
        },
        "Black Coach" : {
            baseSize: "170 x 105mm",
            notes: "",
        },
        "Black Knights" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Blood Knights" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Bloodseeker Palanquin" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Cairn Wraith" : {
            baseSize: "25mm",
            notes: "",
        },
        "Corpse Cart with Balefire Brazier" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Corpse Cart with Unholy Lodestone" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Coven Throne" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Dire Wolves" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Fell Bats" : {
            baseSize: "40mm",
            notes: "",
        },
        "Grave Guard" : {
            baseSize: "25mm",
            notes: "",
        },
        "Hexwraiths" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Mannfred, Mortarch of Night" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Morghast Archai" : {
            baseSize: "60mm",
            notes: "",
        },
        "Morghast Harbingers" : {
            baseSize: "60mm",
            notes: "",
        },
        "Mortis Engine" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Nagash, Supreme Lord of the Undead" : {
            baseSize: "130mm",
            notes: "",
        },
        "Necromancer" : {
            baseSize: "32mm",
            notes: "",
        },
        "Neferata, Mortarch of Blood" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Prince Vhordrai" : {
            baseSize: "130mm",
            notes: "",
        },
        "The Sepulchral Guard" : {
            baseSize: "25mm",
            notes: "",
        },
        "Skeleton Warriors" : {
            baseSize: "25mm",
            notes: "",
        },
        "Spirit Hosts" : {
            baseSize: "50mm",
            notes: "",
        },
        "Terrorgheist" : {
            baseSize: "130mm",
            notes: "",
        },
        "Tomb Banshee" : {
            baseSize: "25mm",
            notes: "",
        },
        "Vampire Lord" : {
            baseSize: "32mm",
            notes: "",
        },
        "Vampire Lord on Nightmare Steed" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Vampire Lord on Zombie Dragon" : {
            baseSize: "130mm",
            notes: "",
        },
        "Vargheists" : {
            baseSize: "50mm",
            notes: "",
        },
        "Wight King with Baleful Tomb Blade" : {
            baseSize: "32mm",
            notes: "",
        },
        "Wight King with Black Axe" : {
            baseSize: "32mm",
            notes: "",
        },
        "Zombie Dragon" : {
            baseSize: "130mm",
            notes: "",
        },
        "Zombies" : {
            baseSize: "25mm",
            notes: "",
        },
    }
}
export default Warscrolls