// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "lion rangers",
    warscrolls: {
        "White Lion Chariots" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "White Lions" : {
            baseSize: "25mm",
            notes: "",
        },
    }
}
export default Warscrolls