// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "lumineth realmlords",
    warscrolls: {
        "Alarith Spirit of the Mountain" : {
            baseSize: "100mm",
            notes: "",
        },
        "Alarith Stoneguard" : {
            baseSize: "32mm",
            notes: "",
        },
        "Alarith Stonemage" : {
            baseSize: "40mm",
            notes: "",
        },
        "Archmage Teclis and Celennar, Spirit of Hysh" : {
            baseSize: "160mm",
            notes: "",
        },
        "Avalenor, the Stoneheart King" : {
            baseSize: "100mm",
            notes: "",
        },
        "Ellania and Ellathor, Eclipsian Warsages" : {
            baseSize: "40mm",
            notes: "",
        },
        "Hurakan Spirit of the Wind" : {
            baseSize: "60mm",
            notes: "",
        },
        "Hurakan Windchargers" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Hurakan Windmage" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Hyshian Twinstones" : {
            baseSize: "50mm",
            notes: "",
        },
        "Lyrior Uthralle, Warden of Ymetrica" : {
            baseSize: "90 x 52.5mm",
            notes: "",
        },
        "Rune of Petrification" : {
            baseSize: "75 x 42mm",
            notes: "",
        },
        "Sanctum of Amyntok" : {
            baseSize: "Custom base",
            notes: "",
        },
        "Scinari Calligrave" : {
            baseSize: "32mm",
            notes: "",
        },
        "Scinari Cathallar" : {
            baseSize: "32mm",
            notes: "",
        },
        "Scinari Loreseeker" : {
            baseSize: "32mm",
            notes: "",
        },
        "Sevireth, Lord of the Seventh Wind" : {
            baseSize: "60mm",
            notes: "",
        },
        "The Light of Eltharion" : {
            baseSize: "50mm",
            notes: "",
        },
        "Vanari Auralan Sentinels" : {
            baseSize: "32mm",
            notes: "",
        },
        "Vanari Auralan Wardens" : {
            baseSize: "32mm",
            notes: "",
        },
        "Vanari Bannerblade" : {
            baseSize: "40mm",
            notes: "",
        },
        "Vanari Bladelords" : {
            baseSize: "32mm",
            notes: "",
        },
        "Vanari Dawnriders" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Vanari Lord Regent" : {
            baseSize: "90 x 52.5mm",
            notes: "",
        },
        "Vanari Starshard Ballista" : {
            baseSize: "80mm",
            notes: "",
        },
    }
}
export default Warscrolls