// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "new  sons of behemat",
    warscrolls: {
        "Mancrusher Gargants" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Bonegrinder Mega-Gargant" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Gatebreaker Mega-Gargant" : {
            baseSize: "130mm",
            notes: "",
        },
        "Kraken-eater Mega-Gargant" : {
            baseSize: "130mm",
            notes: "",
        },
        "Warstomper Mega-Gargant" : {
            baseSize: "130mm",
            notes: "",
        },
    }
}
export default Warscrolls