// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "ossiarch bonereapers",
    warscrolls: {
        "Arch-Kavalos Zandtos" : {
            baseSize: "80mm",
            notes: "",
        },
        "Bone-tithe Shrieker" : {
            baseSize: "90 x 52mm",
            notes: "",
        },
        "Gothizzar Harvester" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Immortis Guard" : {
            baseSize: "50mm",
            notes: "",
        },
        "Katakros, Mortarch of the Necropolis" : {
            baseSize: "120 x 92mm",
            notes: "",
        },
        "Kavalos Deathriders" : {
            baseSize: "60 x 35mm",
            notes: "",
        },
        "Liege-Kavalos" : {
            baseSize: "80mm",
            notes: "",
        },
        "Mortek Crawler" : {
            baseSize: "170 x 105mm",
            notes: "",
        },
        "Mortek Guard" : {
            baseSize: "25mm",
            notes: "",
        },
        "Mortisan Boneshaper" : {
            baseSize: "32mm",
            notes: "",
        },
        "Mortisan Soulmason" : {
            baseSize: "40mm",
            notes: "",
        },
        "Mortisan Soulreaper" : {
            baseSize: "32mm",
            notes: "",
        },
        "Nightmare Predator" : {
            baseSize: "60mm",
            notes: "",
        },
        "Necropolis Stalkers" : {
            baseSize: "50mm",
            notes: "",
        },
        "Soulstealer Carrion" : {
            baseSize: "60mm",
            notes: "",
        },
        "Vokmortian, Master of the Bone-tithe" : {
            baseSize: "40mm",
            notes: "",
        },
    }
}
export default Warscrolls