// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls } from "../types";

const Warscrolls: TFactionWarscrolls = {
    faction: "sylvaneth",
    warscrolls: {
        "Alarielle the Everqueen" : {
            baseSize: "160mm",
            notes: "",
        },
        "Branchwraith" : {
            baseSize: "32mm",
            notes: "",
        },
        "Branchwych" : {
            baseSize: "32mm",
            notes: "",
        },
        "Drycha Hamadreth" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Gladewyrm" : {
            baseSize: "Custom base",
            notes: "",
        },
        "Kurnoth Hunters" : {
            baseSize: "50mm",
            notes: "",
        },
        "Spirit of Durthu" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Spite-Revenants" : {
            baseSize: "32mm",
            notes: "",
        },
        "Spiteswarm Hive" : {
            baseSize: "50mm",
            notes: "",
        },
        "Sylvaneth Dryads" : {
            baseSize: "32mm",
            notes: "",
        },
        "Sylvaneth Wyldwood" : {
            baseSize: "No base",
            notes: "",
        },
        "Tree-Revenants" : {
            baseSize: "32mm",
            notes: "",
        },
        "Treelord" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Treelord Ancient" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
        "Vengeful Skullroot" : {
            baseSize: "105 x 70mm",
            notes: "",
        },
    }
}
export default Warscrolls