// This file is generated by import_data.py
// Do not make changes to it manually, as they will be overwritten in the future
import { TFactionWarscrolls, TWarscrolls } from "./types";
import { tagAndCombine } from "../utils/data";

import AelfWarscrolls from "./data/aelf"
import Beasts_Of_ChaosWarscrolls from "./data/beasts_of_chaos"
import Blades_Of_KhorneWarscrolls from "./data/blades_of_khorne"
import Cities_Of_SigmarWarscrolls from "./data/cities_of_sigmar"
import Cursed_CityWarscrolls from "./data/cursed_city"
import Daemons_Of_ChaosWarscrolls from "./data/daemons_of_chaos"
import Daughters_Of_KhaineWarscrolls from "./data/daughters_of_khaine"
import DestructionWarscrolls from "./data/destruction"
import Disciples_Of_TzeentchWarscrolls from "./data/disciples_of_tzeentch"
import Eldritch_CouncilWarscrolls from "./data/eldritch_council"
import FimirWarscrolls from "./data/fimir"
import Flesheater_CourtsWarscrolls from "./data/flesheater_courts"
import Forbidden_PowerWarscrolls from "./data/forbidden_power"
import FyreslayersWarscrolls from "./data/fyreslayers"
import Gitmob_GrotsWarscrolls from "./data/gitmob_grots"
import Gloomspite_GitzWarscrolls from "./data/gloomspite_gitz"
import GreenskinzWarscrolls from "./data/greenskinz"
import Hedonites_Of_SlaaneshWarscrolls from "./data/hedonites_of_slaanesh"
import Idoneth_DeepkinWarscrolls from "./data/idoneth_deepkin"
import Kharadron_OverlordsWarscrolls from "./data/kharadron_overlords"
import KruleboyzWarscrolls from "./data/kruleboyz"
import Legions_Of_AzgorhWarscrolls from "./data/legions_of_azgorh"
import Legions_Of_NagashWarscrolls from "./data/legions_of_nagash"
import Lion_RangersWarscrolls from "./data/lion_rangers"
import Lumineth_RealmlordsWarscrolls from "./data/lumineth_realmlords"
import Maggotkin_Of_NurgleWarscrolls from "./data/maggotkin_of_nurgle"
import Malign_SorceryWarscrolls from "./data/malign_sorcery"
import Monsters_Of_ChaosWarscrolls from "./data/monsters_of_chaos"
import Monsters_Of_DestructionWarscrolls from "./data/monsters_of_destruction"
import Monsters_Of_OrderWarscrolls from "./data/monsters_of_order"
import NighthauntWarscrolls from "./data/nighthaunt"
import Ogor_MawtribesWarscrolls from "./data/ogor_mawtribes"
import OrderWarscrolls from "./data/order"
import Order_DraconisWarscrolls from "./data/order_draconis"
import Orruk_WarclansWarscrolls from "./data/orruk_warclans"
import Ossiarch_BonereapersWarscrolls from "./data/ossiarch_bonereapers"
import SeraphonWarscrolls from "./data/seraphon"
import SkavenWarscrolls from "./data/skaven"
import Slaves_To_DarknessWarscrolls from "./data/slaves_to_darkness"
import Sons_Of_BehematWarscrolls from "./data/sons_of_behemat"
import Soulblight_GravelordsWarscrolls from "./data/soulblight_gravelords"
import Stormcast_EternalsWarscrolls from "./data/stormcast_eternals"
import SylvanethWarscrolls from "./data/sylvaneth"
import Tamurkhans_HordeWarscrolls from "./data/tamurkhans_horde"

export const UntaggedWarscrolls: TFactionWarscrolls[] = [
    AelfWarscrolls,
    Beasts_Of_ChaosWarscrolls,
    Blades_Of_KhorneWarscrolls,
    Cities_Of_SigmarWarscrolls,
    Cursed_CityWarscrolls,
    Daemons_Of_ChaosWarscrolls,
    Daughters_Of_KhaineWarscrolls,
    DestructionWarscrolls,
    Disciples_Of_TzeentchWarscrolls,
    Eldritch_CouncilWarscrolls,
    FimirWarscrolls,
    Flesheater_CourtsWarscrolls,
    Forbidden_PowerWarscrolls,
    FyreslayersWarscrolls,
    Gitmob_GrotsWarscrolls,
    Gloomspite_GitzWarscrolls,
    GreenskinzWarscrolls,
    Hedonites_Of_SlaaneshWarscrolls,
    Idoneth_DeepkinWarscrolls,
    Kharadron_OverlordsWarscrolls,
    KruleboyzWarscrolls,
    Legions_Of_AzgorhWarscrolls,
    Legions_Of_NagashWarscrolls,
    Lion_RangersWarscrolls,
    Lumineth_RealmlordsWarscrolls,
    Maggotkin_Of_NurgleWarscrolls,
    Malign_SorceryWarscrolls,
    Monsters_Of_ChaosWarscrolls,
    Monsters_Of_DestructionWarscrolls,
    Monsters_Of_OrderWarscrolls,
    NighthauntWarscrolls,
    Ogor_MawtribesWarscrolls,
    OrderWarscrolls,
    Order_DraconisWarscrolls,
    Orruk_WarclansWarscrolls,
    Ossiarch_BonereapersWarscrolls,
    SeraphonWarscrolls,
    SkavenWarscrolls,
    Slaves_To_DarknessWarscrolls,
    Sons_Of_BehematWarscrolls,
    Soulblight_GravelordsWarscrolls,
    Stormcast_EternalsWarscrolls,
    SylvanethWarscrolls,
    Tamurkhans_HordeWarscrolls,
]
export const Warscrolls: TWarscrolls = tagAndCombine(UntaggedWarscrolls)